"""Film 15: When To Trust A Feeling (illusion of validity and expert intuition, Ch 20 and 22)."""
import sys
import filmgen as G

DL = "https://thedecisionlab.com/biases"

FILM = {
    "slug": "diana-gut-feeling", "comp_id": "DianaGutFeeling",
    "title": "When To Trust A Feeling", "position": "15 of 18", "chapters": "Ch 20 and 22",
    "source_url": DL, "source_title": "Cognitive Biases - The Decision Lab",
    "topic": "The illusion of validity and the two conditions for trusting intuition, told for an 8-year-old as when a gut feeling is worth listening to",
    "summary": ("Film 15 of the series. Chapters 20 and 22. Confidence is produced by the coherence of a story and "
                "not by the quality of the evidence, so feeling certain is no guide to being right. Kahneman gives "
                "two conditions under which an intuition can be trusted: the situation must be regular enough to "
                "be predictable, and the person must have had long practice in it with quick, clear feedback. For "
                "a child this separates the gut feeling about a bicycle wobble, which is earned, from the gut "
                "feeling about who will be nice to her, which is not."),
    "existing": [
        {"title": "Jane the Brain (NIMH)", "url": G.NIMH, "source": "government site",
         "angle": "Coping with big feelings", "what_it_covers": "Emotions generally, not when a hunch is reliable"},
        {"title": "Children's confidence-building material", "url": G.SCH, "source": "web",
         "angle": "Trust yourself, believe in your instincts",
         "what_it_covers": "Tells a child to trust her gut without ever saying when a gut is worth trusting"},
        {"title": "Cognitive Biases - The Decision Lab", "url": DL, "source": "reference site",
         "angle": "Adult reference explainer", "what_it_covers": "Expert intuition through chess, firefighting and stock-picking framings"}],
    "saturated": ["Trust-your-instincts confidence coaching",
                  "Adult expertise, chess and professional-judgement framings"],
    "gaps": ["Giving a child two concrete tests for whether a particular hunch is worth anything",
             "Saying plainly that feeling certain is not evidence of being right",
             "Separating the practised gut feeling from the unpractised one, using her own examples"],
    "data_points": [
        ("Confidence reflects the coherence of the story the mind has built, not the amount or quality of evidence.",
         DL, "Thinking, Fast and Slow, Ch 20", "secondary_source", "counterintuitive",
         "the spine: sure is not the same as right"),
        ("An intuition can be trusted only where the environment is regular enough to be predictable.",
         G.SN, "Thinking, Fast and Slow, Ch 22", "secondary_source", "expected",
         "the first test: does this thing behave the same way most times"),
        ("The second condition is prolonged practice with rapid, unambiguous feedback.",
         G.SN, "Thinking, Fast and Slow, Ch 22", "secondary_source", "expected",
         "the second test: have you done it many times and found out quickly each time"),
        ("Subjective confidence is a poor guide to accuracy even among trained professionals.",
         G.SN, "Thinking, Fast and Slow, Ch 20", "secondary_source", "surprising",
         "why the film refuses to treat certainty as a signal"),
        ("By age 8 to 9 children can classify their own reasoning against explicit criteria.",
         G.PQ, "Pennequin et al., British Journal of Educational Psychology (2020)", "primary_source",
         "expected", "age appropriateness of a two-question test")],
    "knowledge_level": ("Age 8. Has seen films 1 to 14 and owns the fast one, the story machine, the anchor, the "
                        "see-saw, the tiny spoon, the ordinary street, the shrinking circle, the worn path and the fog."),
    "questions": ["When should I listen to a feeling and when should I ignore it?",
                  "Why am I sometimes completely sure and completely wrong?",
                  "How does my body know things my head does not?"],
    "misconceptions": [
        ("A strong feeling means I am probably right", "Strength of feeling comes from the story fitting together, not from evidence.", "Ch 20"),
        ("Gut feelings are always rubbish", "In practised, regular situations they are excellent and faster than thinking.", "Ch 22"),
        ("Grown-ups' certainty means they know", "Confidence is a poor guide to accuracy, including in adults.", "Ch 20")],
    "pain_points": ["Being sure and being wrong, and not knowing which times to trust",
                    "Being told to trust her instincts about things she has no practice in"],
    "angles": [
        ("The Bicycle and the Stranger", "narrative",
         "Your body knows the bicycle. It does not know the stranger. Same feeling, two different values.",
         "Two concrete situations she has both experienced, one where the hunch is earned and one where it is not.",
         ["Ch 22"]),
        ("Two Questions", "evergreen", "Does it behave the same way most times, and have I done it a lot and found out quickly?",
         "A two-question test is exactly what Kahneman gives, and it is small enough for a child to hold.",
         ["Ch 22"]),
        ("Sure Is Not Right", "contrarian", "How certain you feel tells you nothing about whether you are correct.",
         "Directly contradicts trust-your-instincts advice, which is the dominant message she receives.", ["Ch 20"])],
    "kahneman": "Trust intuition only in regular environments learned through prolonged practice with rapid feedback.",
    "excluded": ["The stock-picking and clinical-prediction studies, which need adult context.",
                 "Any suggestion that she should never trust herself.",
                 "Anything from the priming or ego-depletion chapters."],
    "concepts": [
        {"id": "c1", "title": "When To Trust A Feeling",
         "hook": "Your hands knew the bicycle was going to wobble before you did. So why were you so sure about that girl?",
         "narrative_structure": "story",
         "visual_approach": "Two doors side by side on cream paper. One has a well-worn handle polished by use; the other is brand new and untouched.",
         "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old",
         "target_platform": "generic", "target_duration_seconds": 155,
         "key_points": ["A practised feeling is real knowledge arriving fast",
                        "An unpractised feeling is a story arriving fast",
                        "They feel exactly the same from the inside",
                        "Test one: does this thing behave the same way most times",
                        "Test two: have I done it many times and found out quickly each time"],
         "core_message": "The feeling is not the evidence. Where the feeling came from is the evidence.",
         "cta": "When you have a strong feeling, ask whether you have practised this thing and found out quickly each time.",
         "tone": "Respectful of her instincts and honest about their limits.",
         "why_this_works": "It neither tells her to trust herself nor to doubt herself, which is the only honest answer and the one nobody gives children.",
         "grounded_in": ["Ch 20", "Ch 22"]},
        {"id": "c2", "title": "Two Questions", "hook": "Ask two things before you trust a hunch.",
         "narrative_structure": "tutorial", "visual_approach": "A worn door handle beside an untouched one.",
         "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old",
         "target_platform": "generic", "target_duration_seconds": 100,
         "key_points": ["Regular or not", "Practised or not", "Then decide"],
         "core_message": "Two questions.", "cta": "Ask them both.", "tone": "Practical",
         "why_this_works": "The actionable core with nothing behind it, so it becomes the payoff of c1.",
         "grounded_in": ["Ch 22"]},
        {"id": "c3", "title": "Sure Is Not Right", "hook": "Being certain proves nothing at all.",
         "narrative_structure": "comparison", "visual_approach": "Two identical glowing shapes, one resting on a solid block and one on nothing.",
         "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old",
         "target_platform": "generic", "target_duration_seconds": 100,
         "key_points": ["Certainty is a feeling", "Feelings are not evidence", "Look underneath it"],
         "core_message": "Sure is not right.", "cta": "Look under the feeling.", "tone": "Firm",
         "why_this_works": "The hardest idea here, but it needs the bicycle first, so it becomes the middle of c1.",
         "grounded_in": ["Ch 20"]}],
    "rationale": ("c1 begins with a hunch of hers that was genuinely right, which earns the film the right to "
                  "question a different one. Starting from doubt would have made it a lecture."),
    "device_short": "the worn door handle beside the brand-new one",
    "art_direction": ("Series house style. New device: two plain doors on cream paper, one with a handle polished "
                      "and worn smooth by thousands of hands, the other brand new and untouched."),
    "device_lock": ("Two plain simple doors drawn flat on cream paper. A brass handle worn shiny and smooth is a "
                    "practised feeling; an identical handle still dull and new is an unpractised one. Nothing is "
                    "counted and no numeral appears."),
    "anti_patterns": ["asking the image model for an exact count of doors, hands or handles",
                      "two children in one frame", "numerals, labels or lettering of any kind",
                      "drawing another child as the stranger; the unfamiliar person is never shown",
                      "a fully painted background"],
    "tradeoffs": [
        {"tradeoff": "Showing the unfamiliar girl versus keeping her off screen",
         "recommendation": "Keep her off screen",
         "quality_impact": "Drawing a second child would break the one-child lock and would invite Diana to attach the lesson to a real classmate. A closed door carries it."},
        {"tradeoff": "Telling her to trust herself versus giving two tests",
         "recommendation": "Two tests",
         "quality_impact": "Trust-yourself is the advice she already gets and it is wrong half the time. The two conditions are what the chapter actually establishes."}],
    "delivery_style": "warm parent reading a bedtime story, respectful and even-handed",
    "performance_intent": ("The same parent and child, fourteen chapters on. It takes her instincts seriously enough "
                           "to sort them, which is a form of respect rather than doubt."),
    "energy_curve": ("Admiring at the bicycle. Curious at the two handles. Firm at sure is not right. Bright at the "
                     "two questions. Warm and trusting at the close."),
    "pause_policy": "Three genuine silences: after your body simply knew, after they feel identical from the inside, and after two yeses.",
    "sample_section": "s9",
    "human_note": "Section s9 must not sound scolding. It is the honest limit, not a telling-off.",
    "reading_age": "Written for a listener of 8. Illusion of validity, expert intuition and validity never appear as terms.",
    "pause_beats": [{"section": "s2", "purpose": "She remembers her body knowing before she did"},
                    {"section": "s8", "purpose": "She notices the two feelings are indistinguishable"},
                    {"section": "s14", "purpose": "She runs both questions on a real feeling"}],
    "grounded_in": {"s1_to_s3": "Ch 22, skilled intuition in a practised, regular activity",
                    "s4_to_s6": "Ch 22, the two conditions, given as the worn handle",
                    "s7_to_s9": "Ch 20, confidence tracks coherence rather than evidence",
                    "s10_to_s12": "Ch 20 and 22, the same feeling arising from very different provenance",
                    "s13_to_s15": "Ch 22 corrective as a two-question test, plus Pennequin"},
    "guardrails": ["The film never tells her to distrust herself generally; it sorts feelings rather than dismissing them.",
                   "The unfamiliar person is never drawn, so the lesson cannot be pinned on a real classmate.",
                   "No numeral appears in any illustration.",
                   "No priming or ego-depletion material."],
    "sections": [
        ("s1", "The wobble", "You were riding your bike, and before you knew anything, your hands had already moved. You caught the wobble.",
         'You were riding your bike, and before you knew anything, <break time="0.4s"/> your hands had already moved. <break time="0.5s"/> You caught the wobble.',
         1.4, "measured", "warm", ["hands"], "Admiring."),
        ("s2", "Nobody told you", "Nobody told you to. You did not decide. Your body simply knew.",
         'Nobody told you to. <break time="0.4s"/> You did not decide. <break time="0.5s"/> Your body simply knew. <break time="2.5s"/>',
         2.5, "slow", "warm", ["knew"], "Pause beat one. Let her feel proud of it."),
        ("s3", "That is real", "That is a real thing. That is knowing, arriving fast. It is not a guess.",
         'That is a real thing. <break time="0.4s"/> That is knowing, <break time="0.3s"/> arriving fast. <break time="0.5s"/> It is not a guess.',
         1.4, "measured", "steady", ["knowing"], "Firm and respectful."),
        ("s4", "Where it came from", "But where did it come from? From falling off. Lots of times. And finding out straight away, every single time.",
         'But where did it come from? <break time="0.5s"/> From falling off. <break time="0.3s"/> Lots of times. <break time="0.5s"/> And finding out straight away, <break time="0.3s"/> every single time.',
         1.4, "measured", "curious", ["straight away"], "The mechanism."),
        ("s5", "The worn handle", "Picture a door handle in a busy place. Thousands of hands. It goes shiny and smooth. You can see the practice on it.",
         'Picture a door handle in a busy place. <break time="0.4s"/> Thousands of hands. <break time="0.5s"/> It goes shiny and smooth. <break time="0.4s"/> You can see the practice on it.',
         1.4, "measured", "warm", ["smooth"], "Picture-building."),
        ("s6", "The new handle", "Now picture a brand new handle. Nobody has ever touched it. It looks exactly the same shape. But there is nothing on it yet.",
         'Now picture a brand new handle. <break time="0.4s"/> Nobody has ever touched it. <break time="0.5s"/> It looks exactly the same shape. <break time="0.4s"/> But there is nothing on it yet.',
         1.4, "measured", "steady", ["nothing"], "The contrast."),
        ("s7", "The other feeling", "So. There was a girl you had never met, and you were completely certain about what she was like.",
         'So. <break time="0.4s"/> There was a girl you had never met, <break time="0.4s"/> and you were completely certain about what she was like.',
         1.4, "measured", "gentle", ["certain"], "No judgement in the voice."),
        ("s8", "Same feeling", "And that feeling was just as strong as the bicycle one. Exactly as strong. They feel identical from the inside.",
         'And that feeling was just as strong as the bicycle one. <break time="0.4s"/> Exactly as strong. <break time="0.5s"/> They feel identical from the inside. <break time="2.5s"/>',
         2.5, "measured", "curious", ["identical"], "Pause beat two. The hinge of the film."),
        ("s9", "But", "But one handle had thousands of hands on it. And the other one had never been touched.",
         'But one handle had thousands of hands on it. <break time="0.5s"/> And the other one had never been touched.',
         1.4, "slow", "gentle", ["never"], "Honest, never scolding."),
        ("s10", "How sure feels", "Because here is the thing about feeling sure. It does not come from how much you know. It comes from how neatly the story fits together.",
         'Because here is the thing about feeling sure. <break time="0.5s"/> It does not come from how much you know. <break time="0.5s"/> It comes from how neatly the story fits together.',
         1.4, "measured", "steady", ["neatly"], "Call back to the story machine."),
        ("s11", "Grown ups too", "That happens to grown ups as well. Being very certain is not proof of anything. Not even in us.",
         'That happens to grown ups as well. <break time="0.5s"/> Being very certain is not proof of anything. <break time="0.4s"/> Not even in us.',
         1.4, "measured", "wry", ["not even"], "Include yourself."),
        ("s12", "Not never trust", "So this is not, never trust your feelings. Your feelings are brilliant. In the places where they have been practised.",
         'So this is not, <break time="0.3s"/> never trust your feelings. <break time="0.5s"/> Your feelings are brilliant. <break time="0.4s"/> In the places where they have been practised.',
         1.4, "measured", "warm", ["brilliant"], "Reassure properly."),
        ("s13", "The tool", "So here is your fifteenth trick, and it is two little questions. One. Does this thing usually behave the same way?",
         'So here is your fifteenth trick, and it is two little questions. <break time="0.5s"/> One. <break time="0.4s"/> Does this thing usually behave the same way?',
         1.4, "measured", "encouraging", ["usually"], "Bright and clear."),
        ("s14", "Second question", "Two. Have I done this lots of times, and found out quickly each time whether I was right? Two yeses, and your feeling is worth a lot.",
         'Two. <break time="0.4s"/> Have I done this lots of times, and found out quickly each time whether I was right? <break time="0.5s"/> Two yeses, <break time="0.4s"/> and your feeling is worth a lot. <break time="2.5s"/>',
         2.5, "measured", "encouraging", ["two yeses"], "Pause beat three. She should test a real feeling."),
        ("s15", "Landing", "The feeling is not the evidence. Where the feeling came from is the evidence.",
         'The feeling is not the evidence. <break time="0.5s"/> Where the feeling came from is the evidence.',
         0.0, "slow", "tender", ["came from"], "Calm and final. End soft."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl rides a bicycle and leans to one side, correcting a wobble, her hands firm on the handlebars and her expression concentrated."),
        ("sc2", "s2", "NONE", "A close view of two small hands gripping a pair of bicycle handlebars. Only the hands and forearms are visible, with no face and no body."),
        ("sc3", "s3", "DIANA", "The girl sits on the ground beside a bicycle lying on its side, brushing off her knee, unbothered and matter of fact."),
        ("sc4", "s4", "NONE", "One plain bicycle standing upright and alone in the middle of the page, well used, with a slightly worn saddle."),
        ("sc5", "s5", "NONE", "One plain wooden door drawn flat in the middle of the page with a round brass handle worn shiny and smooth, catching the light."),
        ("sc6", "s5", "NONE", "A very close view of one round brass door handle, polished smooth and gleaming from long use."),
        ("sc7", "s6", "NONE", "One plain new wooden door drawn flat in the middle of the page with an identical round brass handle that is dull, matte and completely untouched."),
        ("sc8", "s6", "NONE", "Two identical plain doors side by side on the page. The left door's handle is shiny and worn smooth. The right door's handle is dull and new."),
        ("sc9", "s7", "DIANA", "The girl stands looking towards a closed door with a small certain frown, her mind clearly already made up."),
        ("sc10", "s8", "NONE", "Two identical soft glowing warm shapes side by side in the middle of the page, exactly the same size and brightness as one another."),
        ("sc11", "s9", "NONE", "Two identical soft glowing shapes: the left one resting on a solid worn wooden block, the right one floating in empty space with nothing at all beneath it."),
        ("sc12", "s10", "NONE", "Several plain flat shapes fitted neatly together like a finished jigsaw, forming one smooth tidy panel with no gaps."),
        ("sc13", "s11", "NONE", "One plain adult-sized hand resting confidently on a dull untouched brass door handle. Only the hand and forearm are visible, with no face and no body."),
        ("sc14", "s12", "DIANA", "The girl rides her bicycle easily and confidently with a small pleased smile, relaxed and steady."),
        ("sc15", "s13", "NONE", "One plain wooden door with a worn shiny brass handle, drawn alone in warm light, inviting and familiar."),
        ("sc16", "s14", "DIANA", "The girl pauses with one hand hovering just short of a door handle, thinking before she touches it."),
        ("sc17", "s14", "NONE", "A close view of one worn shiny brass handle and one dull new brass handle lying side by side on the page for comparison."),
        ("sc18", "s15", "DIANA", "The girl stands calm and steady in warm golden light with her hands at her sides, settled and self-possessed."),
    ],
    "heroes": {"sc8", "sc10", "sc11", "sc17", "sc18"},
    "wides": {"sc8", "sc11", "sc12"},
}

DOOR = ("The doors are plain simple flat wooden doors drawn from directly in front on plain empty cream paper, with "
        "no walls, no rooms, no frames and no background scenery. Handles are simple round brass knobs. Do not draw "
        "signs, letters, numbers or markings of any kind.")
GLOW = ("The glowing shapes are plain soft-edged warm rounded forms with nothing inside them: no faces, no "
        "patterns, no writing and no numbers.")

FILM["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc2", "sc3", "sc4", "sc9", "sc12", "sc14", "sc16", "sc18"}),
    "NOICON": (G.NOICON, {"sc1", "sc3", "sc4", "sc9", "sc12", "sc14", "sc16", "sc18"}),
    "DOOR": (DOOR, {"sc5", "sc6", "sc7", "sc8", "sc13", "sc15", "sc16", "sc17"}),
    "GLOW": (GLOW, {"sc10", "sc11"}),
}

if __name__ == "__main__":
    if "init" in sys.argv:
        G.init(FILM)
    if "build" in sys.argv:
        G.build(FILM)
    if "sheet" in sys.argv:
        G.sheet(FILM)
