"""Mindset series, films 10-13 of 25: Friendship (Ch 6) / Shyness (Ch 6) / The voice and its name (Ch 8) / Teaching the voice (Ch 8)."""
import sys
import filmgen as G
from mindset_a import base, SRC

# Proven preventive fix: crossed/close-up laced sneakers reliably hallucinate fake logo lettering.
SHOES = ("Her shoes are simple solid maroon-red slip-on canvas flats with a plain white sole and absolutely no "
         "laces, no eyelets, no stripes and no markings of any kind, like a plain child's house shoe.")

# ---------------------------------------------------------------- FILM 10
FILM10 = {**base(10, "diana-mindset-glad-friend", "DianaGladFriend", "The Friend Who's Glad For You", "Ch 6"),
    "topic": "How to tell a real friend, from Chapter 6's Friendship section, told as Dad explaining that the test is who is glad when good things happen to you",
    "summary": ("Film 10. Chapter 6, 'Friendship.' The book asks a sharper question than the usual one: everyone "
                "knows to ask who stands by you in trouble, but the tougher question is who you can turn to when "
                "GOOD things happen. Your failures don't threaten anyone's self-esteem; your successes do, for "
                "people who need to feel superior. Told through one candle lighting another and losing nothing."),
    "existing": [{"title": "Children's friendship advice about sharing and taking turns", "url": SRC, "source": "web", "angle": "Be kind to your friends",
                  "what_it_covers": "Covers behaviour in the moment without giving a child a way to tell a good friendship from a draining one"},
                 {"title": "'A friend in need is a friend indeed' proverbs", "url": SRC, "source": "web", "angle": "Real friends help in hard times",
                  "what_it_covers": "Tests friendship only by trouble, which is the easier test and misses the harder one"},
                 {"title": "Anti-bullying classroom material", "url": SRC, "source": "classroom material", "angle": "Tell someone if you're being bullied",
                  "what_it_covers": "Handles open cruelty but not the quieter friend who only feels big when you feel small"}],
    "saturated": ["Friend-in-need proverbs that test friendship only by who helps in trouble"],
    "gaps": ["Giving a child the harder, more revealing test: who is genuinely glad when something good happens to you",
             "Naming the quiet pattern where someone builds themselves up by making you feel smaller"],
    "data_points": [("The book's sharper question is not who stands by you in trouble, but who you can turn to when good things happen.", SRC, "Mindset, Ch 6 ('Friendship')", "primary_source", "surprising", "the two-candles device"),
                     ("Your failures and misfortunes don't threaten other people's self-esteem; your successes are what trouble someone who needs to feel superior.", SRC, "Mindset, Ch 6", "primary_source", "surprising", "explains why the good-news test reveals more"),
                     ("In a fixed mindset the underlying idea is 'the lower you are, the better I feel', which can quietly intrude on a friendship.", SRC, "Mindset, Ch 6", "primary_source", "expected", "names the pattern without naming a person")],
    "questions": ["How can I tell if someone is really my friend?", "Why do I feel smaller after being with certain people?", "Is it mean to notice that a friend wasn't happy for me?"],
    "misconceptions": [("A real friend is just someone who helps when things go wrong", "That's the easy test. The harder one is whether they're glad when things go right.", "Ch 6"),
                        ("If someone is fun and clever they must be a good friend", "Someone can be brilliant and fun and still leave you feeling smaller every time.", "Ch 6")],
    "pain_points": ["Feeling flat after telling a friend good news", "Not being able to explain why a friendship feels draining"],
    "angles": [("Two Candles", "narrative", "One candle lighting another loses none of its own light. That's the whole test.", "Gives a child a physical image for a feeling she can't yet name.", ["Ch 6"]),
               ("The Harder Question", "contrarian", "Everyone asks who stands by you in trouble. Ask who's glad when things go right.", "Directly reverses the proverb she'll have already heard.", ["Ch 6"]),
               ("Be That Friend Too", "evergreen", "The test points both ways: are you glad when good things happen to them?", "Turns a test of others into something she can practise herself.", ["Ch 6"])],
    "kahneman": "The revealing test of a friendship is not who helps you in trouble, but who is genuinely glad when good things happen to you.",
    "excluded": ["The book's adult examples of romantic partners and colleagues, and the stereotype-endorsement study, which need adult framing."],
    "concepts": [
        {"id": "c1", "title": "The Friend Who's Glad For You", "hook": "Diana, here's a way to tell a real friend that nobody taught me until I was grown up.", "narrative_structure": "story",
         "visual_approach": "One lit candle tilting to light a second unlit candle, its own flame completely undiminished, both then burning together.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 140,
         "key_points": ["Everyone tests friends by who helps in trouble", "The harder test is who's glad when something good happens", "A candle lighting another loses nothing of its own", "Some people only feel bright when yours is dimmer", "Ask yourself the same question about your own friendships"],
         "core_message": "A candle loses nothing by lighting another one. A real friend already knows that.", "cta": "Next time something good happens, notice who is genuinely glad.", "tone": "Warm and quietly serious.",
         "why_this_works": "It gives her a test she can actually run, for a feeling she can already sense but can't name yet.", "grounded_in": ["Ch 6"]},
        {"id": "c2", "title": "The Harder Question", "hook": "Everyone asks who stands by you in trouble. Ask the other one.", "narrative_structure": "comparison",
         "visual_approach": "Two candles side by side, one leaning away from the other, refusing to share its flame.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 75,
         "key_points": ["Trouble is the easy test, because helping costs a person nothing in pride", "Good news is the hard test, because it asks them to be smaller for a second"],
         "core_message": "Sympathy is easy. Being glad is the real thing.", "cta": "Run the harder test, gently.", "tone": "Clear and honest.",
         "why_this_works": "Names why the familiar proverb is incomplete, folded into c1 as its hinge.", "grounded_in": ["Ch 6"]},
        {"id": "c3", "title": "Be That Friend Too", "hook": "This one points both ways, you know.", "narrative_structure": "tutorial",
         "visual_approach": "Her own candle tilting to light someone else's, warm and freely given.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 65,
         "key_points": ["The test applies to how you treat your friends too", "Being glad for someone costs you nothing you actually needed"],
         "core_message": "Be the one who's glad. It costs you nothing.", "cta": "Be glad out loud when a friend does well.", "tone": "Encouraging.",
         "why_this_works": "Turns a diagnostic into a practice, folded into c1 as its closing beat.", "grounded_in": ["Ch 6"]}],
    "rationale": "c1 carries the full candle arc from the easy test to the hard one to her own practice; c2 and c3 are its hinge and its close, all three sharing one continuous pair of candles.",
    "device_short": "one candle lighting another and losing none of its own flame",
    "art_direction": "New device: two plain simple candles on cream paper, one lit, one unlit, the lit one tilting to share its flame without diminishing.",
    "device_lock": ("Two plain simple candles drawn flat on cream paper, no candlesticks, no holders, no decoration, "
                    "no birthday-cake context, no numerals, no writing. Flames are simple warm teardrop shapes. "
                    "Never show a candle burning down to nothing."),
    "tradeoffs": [{"tradeoff": "Naming a real friend of Diana's versus keeping it entirely general", "recommendation": "Entirely general",
                   "quality_impact": "Naming anyone would turn a tool she can use for life into a verdict on one child; the candles let her apply it herself, privately."}],
    "energy_curve": "Warm and conversational at the opening. Quietly serious through the harder test. Gentle at the draining-friend beat. Encouraging and warm at the close.",
    "sample_section": "s6", "human_note": "Section s6 is the reversal. Say it plainly, not cleverly.",
    "pause_beats": [{"section": "s5", "purpose": "She watches the first candle stay just as bright"}, {"section": "s10", "purpose": "She thinks of who was glad for her last time"}, {"section": "s13", "purpose": "She considers whether she is that friend"}],
    "grounded_in": {"s1_to_s4": "Ch 6, the easy test introduced", "s5_to_s8": "Ch 6, the candle and the harder test", "s9_to_s11": "Ch 6 applied to her own friendships", "s12_to_s15": "Ch 6 corrective, pointing the test at herself"},
    "sections": [
        ("s1", "Setup", "Diana, here's a way to tell a real friend that nobody taught me until I was grown up.", "Diana, here's a way to tell a real friend that nobody taught me until I was grown up.", 1.4, "measured", "warm", ["real friend"], "Conversational, letting her in on something."),
        ("s2", "The usual test", "You've probably heard the usual one. A real friend is the one who helps you when something goes wrong.", "You've probably heard the usual one. <break time=\"0.4s\"/> A real friend is the one who helps you when something goes wrong.", 1.4, "measured", "steady", ["goes wrong"], "Neutral, not dismissive."),
        ("s3", "It's true but easy", "And that's true. It's just the easy test. When you're sad, being kind to you costs nobody anything.", "And that's true. <break time=\"0.4s\"/> It's just the easy test. <break time=\"0.4s\"/> When you're sad, being kind to you costs nobody anything.", 1.4, "measured", "curious", ["easy test"], "The first turn."),
        ("s4", "The candles", "So here's the harder one. Picture two candles. One lit, one not.", "So here's the harder one. <break time=\"0.4s\"/> Picture two candles. <break time=\"0.4s\"/> One lit, one not.", 1.4, "measured", "curious", ["two candles"], "Picture-building."),
        ("s5", "Nothing is lost", "The lit one leans over and lights the other. Now watch its own flame. It hasn't lost a thing.", "The lit one leans over and lights the other. <break time=\"0.4s\"/> Now watch its own flame. <break time=\"0.5s\"/> It hasn't lost a thing. <break time=\"2.5s\"/>", 2.5, "slow", "warm", ["hasn't lost a thing"], "Pause beat one. Let her actually look."),
        ("s6", "The reversal", "So the harder question isn't who helps when things go wrong. It's who's genuinely glad when something goes right for you.", "So the harder question isn't who helps when things go wrong. <break time=\"0.5s\"/> It's who's genuinely glad when something goes right for you.", 1.4, "slow", "steady", ["genuinely glad"], "The heart of the film. Plain, not clever."),
        ("s7", "Why that's harder", "Because your bad days don't cost anyone anything. It's your good days that ask them to be pleased about someone else's light.", "Because your bad days don't cost anyone anything. <break time=\"0.5s\"/> It's your good days that ask them to be pleased about someone else's light.", 1.4, "measured", "curious", ["good days"], "Explain the mechanism honestly."),
        ("s8", "The other kind", "Some people can only feel bright when yours is a bit dimmer. They're not villains. They're just running low themselves.", "Some people can only feel bright when yours is a bit dimmer. <break time=\"0.5s\"/> They're not villains. <break time=\"0.4s\"/> They're just running low themselves.", 1.4, "measured", "gentle", ["running low"], "Compassionate, never contemptuous."),
        ("s9", "How it feels", "You'll know them by how you feel afterwards. A bit smaller. A bit flat. Even when nothing unkind was actually said.", "You'll know them by how you feel afterwards. <break time=\"0.4s\"/> A bit smaller. <break time=\"0.3s\"/> A bit flat. <break time=\"0.4s\"/> Even when nothing unkind was actually said.", 1.4, "measured", "gentle", ["a bit smaller"], "Name the feeling she may already have had."),
        ("s10", "Her turn", "Think about the last good thing that happened to you. Who was actually glad?", "Think about the last good thing that happened to you. <break time=\"0.4s\"/> Who was actually glad? <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["actually glad"], "Pause beat two. Real reflection, no pressure."),
        ("s11", "Keep those ones", "Those are the ones to keep close, Diana. Not the cleverest ones. Not the funniest. Those ones.", "Those are the ones to keep close, Diana. <break time=\"0.4s\"/> Not the cleverest ones. <break time=\"0.3s\"/> Not the funniest. <break time=\"0.4s\"/> Those ones.", 1.4, "measured", "warm", ["keep close"], "Warm and definite."),
        ("s12", "It points both ways", "Now here's the part I have to say carefully. This test points both ways.", "Now here's the part I have to say carefully. <break time=\"0.5s\"/> This test points both ways.", 1.4, "measured", "steady", ["both ways"], "A gentle turn toward her."),
        ("s13", "Her own candle", "When something good happens to your friend, are you glad? Properly glad, not just polite?", "When something good happens to your friend, are you glad? <break time=\"0.4s\"/> Properly glad, not just polite? <break time=\"2.5s\"/>", 2.5, "measured", "gentle", ["properly glad"], "Pause beat three. Honest, not accusing."),
        ("s14", "It costs nothing", "It costs you nothing you actually needed. Your flame stays exactly the same size. That's the whole trick of it.", "It costs you nothing you actually needed. <break time=\"0.4s\"/> Your flame stays exactly the same size. <break time=\"0.4s\"/> That's the whole trick of it.", 1.4, "measured", "warm", ["exactly the same"], "Bring it home to the image."),
        ("s15", "Landing", "I'm glad when good things happen to you, Diana. Every single time. That one's easy for me.", "I'm glad when good things happen to you, Diana. <break time=\"0.5s\"/> Every single time. <break time=\"0.4s\"/> That one's easy for me.", 0.0, "slow", "tender", ["every single time"], "Personal, warm, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl stands listening warmly, open and attentive, a small interested smile."),
        ("sc2", "s2", "NONE", "One plain candle burning alone on the cream page, steady and simple."),
        ("sc3", "s3", "NONE", "The same single lit candle, its flame calm and unremarkable, nothing else in frame."),
        ("sc4", "s4", "NONE", "Two plain candles side by side, the left one lit, the right one unlit."),
        ("sc5", "s5", "NONE", "The lit candle tilted toward the unlit one, their wicks touching, a second flame just catching."),
        ("sc6", "s6", "NONE", "Both candles now burning, side by side, the first flame exactly as large as before."),
        ("sc7", "s7", "DIANA", "The girl looks thoughtful and a little surprised, working something out."),
        ("sc8", "s8", "NONE", "A single candle with a small, low, guttering flame, dim but not out, drawn gently rather than sadly."),
        ("sc9", "s9", "DIANA", "The girl looks quietly deflated, shoulders a little low, honestly flat rather than upset."),
        ("sc10", "s10", "DIANA", "The girl looks upward in thought, hand near her chin, genuinely reflective."),
        ("sc11", "s11", "NONE", "Two candles burning warmly together, close beside each other, both bright."),
        ("sc12", "s12", "DIANA", "The girl looks steady and attentive, taking in something that applies to her."),
        ("sc13", "s13", "DIANA", "The girl looks thoughtful and honest, considering a question about herself."),
        ("sc14", "s14", "NONE", "A close view of one candle flame, warm and full, entirely undiminished."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s5", "NONE", "The moment of lighting, the two wicks touching, warm glow spreading between them."),
        ("sc17", "s6", "NONE", "The two lit candles glowing side by side, warm and equal, a soft pool of light around them."),
        ("sc18", "s15", "NONE", "Two candles burning together in soft evening light, calm and settled, warm halo around both."),
    ],
    "heroes": {"sc5", "sc16", "sc18"}, "wides": set(),
}
FILM10["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "NOICON": (G.NOICON, {"sc1", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "SHOES": (SHOES, {"sc1", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "CANDLE": (("The candles are two plain simple candles drawn flat on cream paper, no candlesticks, no holders, "
                "no decorations, no cake, no numerals and no writing. Flames are simple warm teardrop shapes. "
                "Nothing else appears in the frame."),
               {"sc2", "sc3", "sc4", "sc5", "sc6", "sc8", "sc11", "sc14", "sc16", "sc17", "sc18"}),
}

# ---------------------------------------------------------------- FILM 11
FILM11 = {**base(11, "diana-mindset-first-five-minutes", "DianaFirstFiveMinutes", "The First Five Minutes", "Ch 6"),
    "topic": "Shyness and new situations, from Chapter 6's Shyness section and Jennifer Beer's research, told as Dad explaining that everyone is nervous at the start and the difference is what happens next",
    "summary": ("Film 11. Chapter 6, 'Shyness.' Jennifer Beer filmed hundreds of people meeting a stranger. Shy "
                "people with both mindsets looked equally nervous for the first five minutes. After that, the shy "
                "growth-mindset people showed greater social skill, were more likable, and began to look just like "
                "people who were never shy at all. The nerves were the same; what differed was whether they treated "
                "the situation as a challenge to meet or a risk to avoid."),
    "existing": [{"title": "'Just be confident' advice for shy children", "url": SRC, "source": "web", "angle": "Believe in yourself",
                  "what_it_covers": "Tells a shy child to feel differently, which is the one thing she cannot do on command"},
                 {"title": "Icebreaker and conversation-starter lists", "url": SRC, "source": "classroom material", "angle": "Here are things to say",
                  "what_it_covers": "Supplies scripts but never addresses the nerves themselves or how long they last"},
                 {"title": "'Shy is just who you are' reassurance content", "url": SRC, "source": "web", "angle": "Being shy is fine",
                  "what_it_covers": "Comforts by treating shyness as a fixed trait, which is the exact belief that makes it harder"}],
    "saturated": ["Just-be-confident advice that asks a shy child to feel something on command"],
    "gaps": ["Telling a shy child that the nerves are normal AND time-limited, with the specific research finding about the first five minutes",
             "Separating the feeling of shyness from what shyness is allowed to decide"],
    "data_points": [("In Jennifer Beer's filmed study, shy people with both mindsets looked equally nervous for the first five minutes of meeting someone new.", SRC, "Mindset, Ch 6 ('Shyness')", "primary_source", "surprising", "the whole premise of the film"),
                     ("After those first minutes, the shy growth-mindset people showed greater social skills, were more likable, and began to look just like people who were not shy.", SRC, "Mindset, Ch 6", "primary_source", "surprising", "the payoff: the nerves pass if you stay"),
                     ("The difference was in the approach: growth-mindset shy people treated meeting someone new as a challenge to welcome, while fixed-mindset shy people were more worried about making mistakes.", SRC, "Mindset, Ch 6", "primary_source", "expected", "gives her something to choose rather than something to feel"),
                     ("The book's phrasing is that the shy growth-mindset people take control of their shyness, so that the shyness does not tyrannise them.", SRC, "Mindset, Ch 6", "primary_source", "expected", "the closing reframe: shyness can come along without being in charge")],
    "questions": ["Why do I feel sick when I have to talk to someone new?", "Does being shy mean I'll always find this hard?", "How long does the nervous bit actually last?"],
    "misconceptions": [("Confident people don't feel nervous meeting new people", "In the study everyone looked nervous at first. The difference was what happened after.", "Ch 6"),
                        ("Being shy means you're bad at making friends", "Shyness only stops a friendship if it gets to decide whether you stay.", "Ch 6")],
    "pain_points": ["Leaving or going quiet in the first minutes of meeting someone new", "Believing the nervous feeling is proof she isn't good with people"],
    "angles": [("The First Five Minutes", "data_driven", "Everyone looked nervous at the start. The film only got interesting after that.", "Puts a time limit on a feeling that seems permanent from the inside.", ["Ch 6"]),
               ("Nerves Aren't the Verdict", "contrarian", "The nervous feeling isn't evidence about you. It's just the first five minutes.", "Separates a feeling from a conclusion, which is the actual trap.", ["Ch 6"]),
               ("Bring It With You", "evergreen", "You don't have to stop being shy. You just don't have to let it decide.", "Offers something achievable instead of asking her to become someone else.", ["Ch 6"])],
    "kahneman": "Shy people with a growth mindset were just as nervous for the first five minutes; the difference was that they stayed, and after that they looked like people who were never shy.",
    "excluded": ["The adult dating example of Wetzler's client George, and the therapy framing, which need adult context."],
    "concepts": [
        {"id": "c1", "title": "The First Five Minutes", "hook": "Diana, some researchers filmed hundreds of people meeting a stranger. Here's what the film showed.", "narrative_structure": "data_narrative",
         "visual_approach": "A plain sand timer whose top chamber holds only a small amount of sand, running out quickly, then a calm open space beyond it.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 145,
         "key_points": ["Everyone looked nervous at the start, without exception", "The difference showed up only after the first few minutes", "The ones who stayed stopped looking shy at all", "The nerves were never the problem, leaving was", "You can be nervous and stay anyway"],
         "core_message": "Everyone's sand runs the same at the start. What matters is whether you're still there when it runs out.", "cta": "Next time you meet someone new, stay past the nervous part.", "tone": "Reassuring and factual.",
         "why_this_works": "It replaces 'be confident', which she can't do, with 'stay a bit longer', which she can.", "grounded_in": ["Ch 6"]},
        {"id": "c2", "title": "Nerves Aren't the Verdict", "hook": "That nervous feeling isn't evidence about you.", "narrative_structure": "myth_busting",
         "visual_approach": "The sand timer's falling grains shown close, ordinary and unremarkable rather than alarming.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 75,
         "key_points": ["The nervous feeling is not information about whether you're good with people", "Everyone in the study had it, including the ones who did beautifully"],
         "core_message": "The feeling is real. The conclusion you draw from it is the part that's wrong.", "cta": "Don't read the nerves as a verdict.", "tone": "Steady and clear.",
         "why_this_works": "Breaks the specific inference that turns a feeling into an identity, folded into c1 as its middle beat.", "grounded_in": ["Ch 6"]},
        {"id": "c3", "title": "Bring It With You", "hook": "You don't have to stop being shy.", "narrative_structure": "problem_solution",
         "visual_approach": "The emptied timer resting quietly beside an open, unhurried space.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 70,
         "key_points": ["Shyness is allowed to come along", "It just doesn't get to decide whether you stay or go"],
         "core_message": "Shyness can come with you. It just can't be the one driving.", "cta": "Let it come, but don't let it decide.", "tone": "Warm and freeing.",
         "why_this_works": "Removes the impossible demand to stop feeling shy, folded into c1 as its closing beat.", "grounded_in": ["Ch 6"]}],
    "rationale": "c1 carries the study from the nervous opening to the calm after; c2 and c3 are its middle correction and its closing permission, all three running on the same single timer.",
    "device_short": "a small sand timer whose nervous part runs out quickly",
    "art_direction": "New device: one plain small sand timer drawn simply on cream paper, its top chamber holding only a little sand, shown filling, running, and emptied.",
    "device_lock": ("One plain simple sand timer with two rounded glass chambers and plain wooden caps, drawn flat on "
                    "cream paper. Sand is warm ochre. No numerals, no clock face, no dial, no markings, no writing "
                    "anywhere. Nothing else in the frame."),
    "tradeoffs": [{"tradeoff": "Using a clock face versus a sand timer", "recommendation": "A sand timer",
                   "quality_impact": "A clock face would need numerals, which no illustration in this series may contain; sand shows a quantity running out without a single digit."}],
    "energy_curve": "Curious and factual at the study. Reassuring through the five-minute finding. Warm and freeing at the permission to stay shy. Settled at the close.",
    "sample_section": "s7", "human_note": "Section s7 is the finding itself. Deliver it as good news, because it is.",
    "pause_beats": [{"section": "s5", "purpose": "She watches how little sand there actually is"}, {"section": "s10", "purpose": "She thinks of a time she left before the sand ran out"}, {"section": "s13", "purpose": "She pictures staying one minute longer"}],
    "grounded_in": {"s1_to_s4": "Ch 6, the filmed study set up", "s5_to_s8": "Ch 6, the five-minute finding", "s9_to_s11": "Ch 6 applied to her own experience", "s12_to_s15": "Ch 6 corrective, shyness allowed but not in charge"},
    "sections": [
        ("s1", "Setup", "Diana, some researchers filmed hundreds of people meeting a stranger. Here's what the film showed.", "Diana, some researchers filmed hundreds of people meeting a stranger. <break time=\"0.4s\"/> Here's what the film showed.", 1.4, "measured", "curious", ["filmed"], "Inviting, like sharing something interesting."),
        ("s2", "The nervous ones", "Some of the people were shy. Really shy. Heart going fast, cheeks hot, wanting to leave.", "Some of the people were shy. <break time=\"0.4s\"/> Really shy. <break time=\"0.4s\"/> Heart going fast, cheeks hot, wanting to leave.", 1.4, "measured", "gentle", ["really shy"], "Describe it from the inside, kindly."),
        ("s3", "Everyone looked the same", "And at the start, every single one of them looked nervous. Every one. There was no brave group.", "And at the start, every single one of them looked nervous. <break time=\"0.4s\"/> Every one. <break time=\"0.4s\"/> There was no brave group.", 1.4, "measured", "steady", ["every one"], "This is reassuring news. Deliver it that way."),
        ("s4", "The timer", "Picture a little sand timer. The nervous part is the sand in the top. And there's less of it than you'd think.", "Picture a little sand timer. <break time=\"0.4s\"/> The nervous part is the sand in the top. <break time=\"0.4s\"/> And there's less of it than you'd think.", 1.4, "measured", "curious", ["less of it"], "Picture-building."),
        ("s5", "How little", "About five minutes' worth. That's all. Watch it run.", "About five minutes' worth. <break time=\"0.4s\"/> That's all. <break time=\"0.4s\"/> Watch it run. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["five minutes"], "Pause beat one. Let the sand actually run."),
        ("s6", "The split", "After that, the film got interesting. Because the people split into two groups.", "After that, the film got interesting. <break time=\"0.4s\"/> Because the people split into two groups.", 1.4, "measured", "curious", ["two groups"], "Build the turn."),
        ("s7", "The finding", "The ones who stayed stopped looking shy at all. Warmer, easier, better company. They looked like people who'd never been shy in their lives.", "The ones who stayed stopped looking shy at all. <break time=\"0.5s\"/> Warmer, easier, better company. <break time=\"0.4s\"/> They looked like people who'd never been shy in their lives.", 1.4, "slow", "warm", ["never been shy"], "The finding, and it's good news. Sound like it is."),
        ("s8", "The other group", "The other ones left, or went quiet, while the sand was still falling. And so their nervous part never got to end.", "The other ones left, or went quiet, while the sand was still falling. <break time=\"0.5s\"/> And so their nervous part never got to end.", 1.4, "measured", "gentle", ["never got to end"], "No blame at all in this."),
        ("s9", "Not about being brave", "So it was never about who was braver. Both groups felt exactly the same at the start.", "So it was never about who was braver. <break time=\"0.4s\"/> Both groups felt exactly the same at the start.", 1.4, "measured", "steady", ["exactly the same"], "Remove the character judgement."),
        ("s10", "Her turn", "Think of a time you went quiet, or slipped away, in the first few minutes. I've done it too.", "Think of a time you went quiet, or slipped away, in the first few minutes. <break time=\"0.4s\"/> I've done it too. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["gone quiet"], "Pause beat two. Solidarity, not correction."),
        ("s11", "What it isn't", "That feeling isn't proof you're bad with people, Diana. It's just the sand at the top.", "That feeling isn't proof you're bad with people, Diana. <break time=\"0.4s\"/> It's just the sand at the top.", 1.4, "measured", "tender", ["isn't proof"], "The most important sentence for her. Warm."),
        ("s12", "You can stay shy", "And here's the bit I love. You don't have to stop being shy. Nobody's asking you to become somebody else.", "And here's the bit I love. <break time=\"0.5s\"/> You don't have to stop being shy. <break time=\"0.4s\"/> Nobody's asking you to become somebody else.", 1.4, "measured", "warm", ["somebody else"], "Genuine relief in the voice."),
        ("s13", "One minute longer", "Shyness can come with you. It just doesn't get to decide when you leave. So next time, stay one minute longer than it wants to.", "Shyness can come with you. <break time=\"0.4s\"/> It just doesn't get to decide when you leave. <break time=\"0.5s\"/> So next time, stay one minute longer than it wants to. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["one minute longer"], "Pause beat three. The actual, small, doable tool."),
        ("s14", "Then another", "Then the minute after that. That's the whole method. There isn't a cleverer one.", "Then the minute after that. <break time=\"0.4s\"/> That's the whole method. <break time=\"0.4s\"/> There isn't a cleverer one.", 1.4, "measured", "warm", ["whole method"], "Plain and honest."),
        ("s15", "Landing", "The sand always runs out, Diana. Every single time. Just be there when it does.", "The sand always runs out, Diana. <break time=\"0.5s\"/> Every single time. <break time=\"0.4s\"/> Just be there when it does.", 0.0, "slow", "tender", ["always runs out"], "Personal, warm, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl listens with curious interest, head slightly tilted, engaged."),
        ("sc2", "s2", "DIANA", "The girl stands with her hands held together in front of her, shoulders slightly drawn in, quietly nervous but not distressed."),
        ("sc3", "s3", "NONE", "Several small plain figure silhouettes standing in a loose row, all in the same slightly hunched nervous posture, identical to one another."),
        ("sc4", "s4", "NONE", "One plain small sand timer standing alone on the cream page, its top chamber holding a small amount of warm ochre sand."),
        ("sc5", "s5", "NONE", "The sand timer mid-run, a thin stream of sand falling from the top chamber into the bottom."),
        ("sc6", "s6", "NONE", "The sand timer nearly empty in the top, only a few grains left falling."),
        ("sc7", "s7", "NONE", "Two plain figure silhouettes standing comfortably close together in relaxed, open postures, at ease with each other."),
        ("sc8", "s8", "NONE", "One plain figure silhouette walking away alone toward the edge of the page, the sand timer still running behind it."),
        ("sc9", "s9", "DIANA", "The girl looks thoughtful and steady, taking in an idea calmly."),
        ("sc10", "s10", "DIANA", "The girl looks down in quiet honest thought, remembering something."),
        ("sc11", "s11", "DIANA", "The girl looks up, gently reassured, the beginning of relief in her expression."),
        ("sc12", "s12", "DIANA", "The girl looks openly relieved and warm, a small genuine smile."),
        ("sc13", "s13", "DIANA", "The girl stands a little straighter, quietly resolved, calm and determined."),
        ("sc14", "s14", "NONE", "The sand timer fully emptied, all the sand resting calmly in the bottom chamber."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s5", "NONE", "A close view of the falling stream of sand inside the timer, warm and ordinary."),
        ("sc17", "s7", "NONE", "The two relaxed figure silhouettes together, warmly lit, clearly comfortable in each other's company."),
        ("sc18", "s15", "NONE", "The emptied sand timer resting in warm evening light, calm and settled, all its sand safely at the bottom."),
    ],
    "heroes": {"sc7", "sc14", "sc17", "sc18"}, "wides": {"sc3"},
}
FILM11["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc2", "sc9", "sc10", "sc11", "sc12", "sc13", "sc15"}),
    "NOICON": (G.NOICON, {"sc1", "sc2", "sc9", "sc10", "sc11", "sc12", "sc13", "sc15"}),
    "SHOES": (SHOES, {"sc1", "sc2", "sc9", "sc10", "sc11", "sc12", "sc13", "sc15"}),
    "TIMER": (("The timer is one plain simple sand timer with two rounded glass chambers and plain wooden caps, "
               "drawn flat on cream paper. Sand is warm ochre. Absolutely no numerals, no clock face, no dial, "
               "no scale markings and no writing anywhere. Nothing else in the frame."),
              {"sc4", "sc5", "sc6", "sc8", "sc14", "sc16", "sc18"}),
    "FIGURES": (("Figures are plain simple solid silhouette shapes with no facial features, no clothing detail and "
                 "no accessories, drawn flat on cream paper. No crowd, no scenery, no background of any kind."),
                {"sc3", "sc7", "sc8", "sc17"}),
}

# ---------------------------------------------------------------- FILM 12
FILM12 = {**base(12, "diana-mindset-give-it-a-name", "DianaGiveItAName", "The Voice That Says You Can't", "Ch 8"),
    "topic": "Noticing the fixed-mindset voice and giving it a name, from Chapter 8's four-step journey, told as Dad introducing the small creature that shows up when things get hard",
    "summary": ("Film 12. Chapter 8, 'The Journey to a (True) Growth Mindset', steps one to three. Everyone has a "
                "fixed-mindset voice; it turns up at predictable moments; and the book's own instruction is to give "
                "it a name. Dweck describes a grade-school teacher whose class named theirs — Scared Sally, Lazy "
                "Larry, Anxious Andy, Helpless Hannah — and one boy whose Dumping Dan finally let him work."),
    "existing": [{"title": "Positive-affirmation scripts for children", "url": SRC, "source": "web", "angle": "Say nice things to yourself",
                  "what_it_covers": "Adds a second voice on top without ever helping a child notice the first one"},
                 {"title": "'Ignore your negative thoughts' advice", "url": SRC, "source": "web", "angle": "Push it away",
                  "what_it_covers": "Asks a child to suppress something she can't yet even identify, which mostly teaches her it's shameful"},
                 {"title": "Growth-mindset classroom charts", "url": SRC, "source": "classroom material", "angle": "Say 'not yet' instead",
                  "what_it_covers": "Prescribes the replacement sentence without the noticing step that has to come first"}],
    "saturated": ["Affirmation scripts that add a nicer voice without ever identifying the unkind one"],
    "gaps": ["Teaching a child to NOTICE the voice before trying to answer it", "Using the book's own naming instruction, which it documents being used with primary-school children"],
    "data_points": [("The first step of the book's journey is to accept that everyone has some fixed mindset in them; it calls this welcoming yourself to the human race rather than a shameful admission.", SRC, "Mindset, Ch 8 ('The Journey to a (True) Growth Mindset')", "primary_source", "expected", "why the film opens with 'everyone has one'"),
                     ("The second step is to notice the triggers: taking on a big new challenge, hitting dead ends, failing at something, or meeting someone better than you at the thing you pride yourself on.", SRC, "Mindset, Ch 8", "primary_source", "expected", "the list of moments the creature turns up"),
                     ("The third step is literally to give the fixed-mindset persona a name; the book records a grade-school class doing exactly this, naming theirs Scared Sally, Lazy Larry, Anxious Andy and Helpless Hannah.", SRC, "Mindset, Ch 8", "primary_source", "surprising", "the naming instruction, straight from the book, already tested on children"),
                     ("One boy in that class named his Dumping Dan, and once the teacher worked with him and the named voice, the book reports his growth was tremendous.", SRC, "Mindset, Ch 8", "primary_source", "surprising", "shows the tool working for a child, not just an adult")],
    "questions": ["Why does a voice in my head tell me I can't do things?", "Does everyone have one, or is it just me?", "When does it usually turn up?"],
    "misconceptions": [("Only people who lack confidence have that voice", "The book's position is that everyone has one; not a single student asked could claim otherwise.", "Ch 8"),
                        ("You should push the voice away and ignore it", "You can't ignore what you haven't noticed. Noticing comes first, and the book says not to judge it.", "Ch 8")],
    "pain_points": ["Believing the discouraging voice is simply the truth about herself", "Not having any way to separate herself from the thought"],
    "angles": [("Give It a Name", "narrative", "The book tells you to name it. A class of school children did, and it worked.", "Turns an overwhelming inner experience into a small, separate, named thing.", ["Ch 8"]),
               ("Everyone Has One", "evergreen", "Not one student, asked directly, could say they didn't have one.", "Removes the shame that stops a child mentioning it at all.", ["Ch 8"]),
               ("It Turns Up On Schedule", "data_driven", "It arrives at predictable moments: new challenges, dead ends, and people better than you.", "Makes the voice predictable, which is the first step to it being manageable.", ["Ch 8"])],
    "kahneman": "Everyone has a fixed-mindset voice, it arrives at predictable moments, and the book's own instruction is to give it a name.",
    "excluded": ["The adult workplace personas Duane and Ianni, and the university students' named personas, which are adult in tone and content."],
    "concepts": [
        {"id": "c1", "title": "The Voice That Says You Can't", "hook": "Diana, there's a small voice that turns up when things get hard. I want you to meet it properly.", "narrative_structure": "story",
         "visual_approach": "A small round soft grey creature that appears at the edge of the page whenever something is difficult, never frightening, more anxious than menacing.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 145,
         "key_points": ["Everyone has one, including me", "It turns up at the same few moments every time", "It isn't the truth, it's just a voice", "The book says to give it a name", "A whole class of children did exactly that"],
         "core_message": "It's not you. It's a small thing that visits you. And things that have names are much easier to handle.", "cta": "Notice when it turns up, and give it a name.", "tone": "Warm, matter-of-fact, unafraid.",
         "why_this_works": "It converts something that feels like the truth about herself into a separate small creature with a name.", "grounded_in": ["Ch 8"]},
        {"id": "c2", "title": "Everyone Has One", "hook": "Not one person asked could say they didn't have one.", "narrative_structure": "myth_busting",
         "visual_approach": "Several plain figures, each with the same small grey creature beside them, entirely ordinary.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 70,
         "key_points": ["Having the voice is not a defect or a rare problem", "Everyone is carrying one, including the people who look fearless"],
         "core_message": "Having one isn't the problem. Thinking you're the only one is.", "cta": "Stop treating it as your private fault.", "tone": "Reassuring.",
         "why_this_works": "Removes shame first, because a child who feels ashamed won't examine it, folded into c1 as its opening move.", "grounded_in": ["Ch 8"]},
        {"id": "c3", "title": "It Turns Up On Schedule", "hook": "It arrives at exactly the same few moments, every time.", "narrative_structure": "timeline",
         "visual_approach": "The same small creature appearing three times in a row at three different difficult moments.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 75,
         "key_points": ["Its arrival is predictable, not random", "Knowing when it comes means you can see it coming"],
         "core_message": "It's not random. It has a timetable, and you can learn it.", "cta": "Learn the moments it shows up.", "tone": "Curious and practical.",
         "why_this_works": "Makes an overwhelming feeling into something with a pattern, folded into c1 as its middle section.", "grounded_in": ["Ch 8"]}],
    "rationale": "c1 carries the whole introduction from 'everyone has one' through the triggers to the naming; c2 and c3 are its opening reassurance and its middle pattern, all three following one small creature.",
    "device_short": "a small soft grey creature that turns up whenever something is hard",
    "art_direction": "New device: one small round soft grey creature with simple dot eyes, gentle and slightly anxious rather than frightening, appearing at the edge of scenes.",
    "device_lock": ("The creature is one small round soft grey blob-shaped creature with two simple dot eyes and no "
                    "mouth, about the size of a cat, drawn flat on cream paper. It is gentle and a little worried "
                    "looking, never scary, never sharp, never a monster, no teeth, no claws, no shadow-horror "
                    "styling. No numerals, no writing, no speech bubbles."),
    "tradeoffs": [{"tradeoff": "Drawing the voice as a scary shadow versus a small soft anxious creature", "recommendation": "A small soft anxious creature",
                   "quality_impact": "A frightening rendering would make the voice feel more powerful, which is the opposite of the film's purpose; the book's own framing is that the persona is trying to protect you."}],
    "energy_curve": "Warm and matter-of-fact at the introduction. Curious through the triggers. Light and slightly playful at the naming. Warm and steady at the close.",
    "sample_section": "s12", "human_note": "Section s12 is the naming instruction. Keep it light, almost playful — that lightness is the whole point.",
    "pause_beats": [{"section": "s6", "purpose": "She recognises one of the moments as her own"}, {"section": "s10", "purpose": "She thinks about what hers says"}, {"section": "s13", "purpose": "She picks a name for it"}],
    "grounded_in": {"s1_to_s4": "Ch 8 step 1, everyone has one", "s5_to_s8": "Ch 8 step 2, the triggers", "s9_to_s11": "Ch 8 applied to her own voice", "s12_to_s15": "Ch 8 step 3, giving it a name"},
    "sections": [
        ("s1", "Setup", "Diana, there's a small voice that turns up when things get hard. I want you to meet it properly.", "Diana, there's a small voice that turns up when things get hard. <break time=\"0.4s\"/> I want you to meet it properly.", 1.4, "measured", "warm", ["meet it"], "Matter-of-fact, unafraid, like introducing someone."),
        ("s2", "What it says", "It says things like, maybe you're just not good at this. Or, everyone's going to find out.", "It says things like, <break time=\"0.3s\"/> maybe you're just not good at this. <break time=\"0.4s\"/> Or, everyone's going to find out.", 1.4, "measured", "steady", ["not good at this"], "Quote it plainly, without drama."),
        ("s3", "Everyone has one", "Here's the first thing to know. Everybody has one. Every single person. I have one too.", "Here's the first thing to know. <break time=\"0.4s\"/> Everybody has one. <break time=\"0.4s\"/> Every single person. <break time=\"0.4s\"/> I have one too.", 1.4, "measured", "warm", ["everybody"], "The shame-removal beat. Genuine."),
        ("s4", "Not a fault", "So it isn't a fault in you. It's more like, welcome to being a person.", "So it isn't a fault in you. <break time=\"0.4s\"/> It's more like, welcome to being a person.", 1.4, "measured", "gentle", ["welcome"], "Light, almost amused."),
        ("s5", "It has a timetable", "The second thing is that it doesn't turn up randomly. It has a timetable.", "The second thing is that it doesn't turn up randomly. <break time=\"0.4s\"/> It has a timetable.", 1.4, "measured", "curious", ["timetable"], "Introduce the pattern."),
        ("s6", "The moments", "It comes when you're about to try something big. When you've been stuck a long time. And when somebody's better than you at your favourite thing.", "It comes when you're about to try something big. <break time=\"0.4s\"/> When you've been stuck a long time. <break time=\"0.4s\"/> And when somebody's better than you at your favourite thing. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["your favourite thing"], "Pause beat one. She'll recognise at least one."),
        ("s7", "Recognise it", "You know those moments, don't you. That's not a coincidence. That's its schedule.", "You know those moments, don't you. <break time=\"0.4s\"/> That's not a coincidence. <break time=\"0.4s\"/> That's its schedule.", 1.4, "measured", "warm", ["its schedule"], "Confirming, not testing."),
        ("s8", "Just watch it", "And here's what the book says to do first, which surprised me. Don't argue with it. Don't tell it off. Just notice it.", "And here's what the book says to do first, which surprised me. <break time=\"0.5s\"/> Don't argue with it. <break time=\"0.3s\"/> Don't tell it off. <break time=\"0.4s\"/> Just notice it.", 1.4, "measured", "steady", ["just notice"], "Genuinely surprised tone."),
        ("s9", "Why not fight it", "Because you can't do anything about something you haven't even spotted yet. Noticing has to come first.", "Because you can't do anything about something you haven't even spotted yet. <break time=\"0.4s\"/> Noticing has to come first.", 1.4, "measured", "steady", ["comes first"], "Plain logic."),
        ("s10", "Her turn", "So think. What does yours say to you? What are its actual words?", "So think. <break time=\"0.4s\"/> What does yours say to you? <break time=\"0.4s\"/> What are its actual words? <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["actual words"], "Pause beat two. Genuine, unhurried."),
        ("s11", "It's not you", "Notice something. You could hear those words. Which means they're something you're listening to, not something you are.", "Notice something. <break time=\"0.4s\"/> You could hear those words. <break time=\"0.5s\"/> Which means they're something you're listening to, <break time=\"0.4s\"/> not something you are.", 1.4, "slow", "tender", ["not something you are"], "The most important line in the film. Slow."),
        ("s12", "Give it a name", "Now the strange bit, and this is straight out of the book. Give it a name.", "Now the strange bit, and this is straight out of the book. <break time=\"0.5s\"/> Give it a name.", 1.4, "measured", "warm", ["a name"], "Light, playful. The lightness is the point."),
        ("s13", "The class that did it", "A whole class of school kids did this. Theirs were called things like Scared Sally and Lazy Larry. One boy called his Dumping Dan. What's yours called?", "A whole class of school kids did this. <break time=\"0.4s\"/> Theirs were called things like Scared Sally and Lazy Larry. <break time=\"0.4s\"/> One boy called his Dumping Dan. <break time=\"0.5s\"/> What's yours called? <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["what's yours called"], "Pause beat three. She should actually pick one."),
        ("s14", "Why it works", "It sounds silly. It isn't. Once a thing has a name, it's just a visitor. And a visitor is a lot smaller than the truth.", "It sounds silly. <break time=\"0.4s\"/> It isn't. <break time=\"0.4s\"/> Once a thing has a name, it's just a visitor. <break time=\"0.4s\"/> And a visitor is a lot smaller than the truth.", 1.4, "measured", "warm", ["just a visitor"], "Land the mechanism."),
        ("s15", "Landing", "Mine has a name too, Diana. I'll tell you it one day. Next time, I'll show you what to do when yours turns up.", "Mine has a name too, Diana. <break time=\"0.4s\"/> I'll tell you it one day. <break time=\"0.5s\"/> Next time, I'll show you what to do when yours turns up.", 0.0, "slow", "tender", ["one day"], "Personal, warm, and a genuine hook into the next film."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl stands attentively, calm and curious, listening to something new."),
        ("sc2", "s2", "NONE", "One small round soft grey creature sitting alone on the cream page, looking slightly worried."),
        ("sc3", "s3", "NONE", "Three plain figure silhouettes standing in a row, each with an identical small grey creature sitting beside their feet."),
        ("sc4", "s4", "DIANA", "The girl looks gently amused and relieved, a small smile, tension easing."),
        ("sc5", "s5", "NONE", "The small grey creature standing alone, alert, as though waiting for something."),
        ("sc6", "s6", "NONE", "The same small grey creature shown three times across the page in a row, each time in a slightly different waiting posture."),
        ("sc7", "s7", "DIANA", "The girl looks recognising and a little surprised, connecting something."),
        ("sc8", "s8", "NONE", "The small grey creature sitting quietly while being calmly observed, entirely unthreatening."),
        ("sc9", "s9", "DIANA", "The girl looks thoughtful and steady, working through an idea."),
        ("sc10", "s10", "DIANA", "The girl looks inward in honest thought, hand near her chin."),
        ("sc11", "s11", "NONE", "The small grey creature and a plain figure silhouette standing clearly apart from each other, a visible gap between them."),
        ("sc12", "s12", "DIANA", "The girl looks up with dawning interest, caught by an unexpected idea."),
        ("sc13", "s13", "DIANA", "The girl looks playful and thoughtful, choosing something, a small smile."),
        ("sc14", "s14", "NONE", "The small grey creature sitting calmly, now noticeably smaller in the frame, quite ordinary."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s11", "NONE", "A wider view of the plain figure and the small grey creature standing apart, the space between them clear and warm."),
        ("sc17", "s6", "NONE", "The small grey creature alone, drawn softly and sympathetically, gently anxious rather than menacing."),
        ("sc18", "s15", "NONE", "The small grey creature sitting quietly in warm evening light, calm, small and entirely harmless."),
    ],
    "heroes": {"sc11", "sc14", "sc16", "sc18"}, "wides": {"sc3", "sc16"},
}
FILM12["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc4", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "NOICON": (G.NOICON, {"sc1", "sc4", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "SHOES": (SHOES, {"sc1", "sc4", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "CREATURE": (("The creature is one small round soft grey blob-shaped creature with two simple dot eyes and no "
                  "mouth, roughly the size of a cat, drawn flat on cream paper. It is gentle and slightly worried, "
                  "never scary, never sharp, no teeth, no claws, no horns, no shadow-monster styling. Plain figure "
                  "silhouettes have no facial features and no clothing detail. No numerals, no writing, no speech "
                  "bubbles, no thought bubbles, no background scenery."),
                 {"sc2", "sc3", "sc5", "sc6", "sc8", "sc11", "sc14", "sc16", "sc17", "sc18"}),
}

# ---------------------------------------------------------------- FILM 13
FILM13 = {**base(13, "diana-mindset-teach-the-voice", "DianaTeachTheVoice", "Teach It a New Way", "Ch 8"),
    "topic": "What to do once the fixed-mindset voice has a name, from Chapter 8's fourth step, told as Dad explaining that the voice was trying to protect her and can be brought along rather than banished",
    "summary": ("Film 13. Chapter 8, step four of the journey, and the close of the Mindset half of the series. The "
                "book's instruction is not to suppress or ban the fixed-mindset persona but to educate it and take "
                "it along: thank it for its input, explain why you're going ahead anyway, and ask it to come with "
                "you. Its central insight is that the persona was born to protect you and keep you safe, but has "
                "developed very limiting ways of doing it."),
    "existing": [{"title": "'Silence your inner critic' self-help content", "url": SRC, "source": "web", "angle": "Shut it down",
                  "what_it_covers": "Frames the voice as an enemy to defeat, which the book explicitly does not do"},
                 {"title": "Children's confidence-building exercises", "url": SRC, "source": "classroom material", "angle": "Replace bad thoughts with good ones",
                  "what_it_covers": "Swaps the sentence without addressing why the voice showed up in the first place"},
                 {"title": "'Fake it till you make it' advice", "url": SRC, "source": "web", "angle": "Act confident anyway",
                  "what_it_covers": "Asks a child to perform a feeling rather than understand and work with the one she has"}],
    "saturated": ["Silence-your-inner-critic content that treats the voice as an enemy"],
    "gaps": ["Using the book's actual instruction — educate the voice and bring it with you — instead of the popular one, which is to defeat it",
             "Explaining to a child that the discouraging voice originally showed up to protect her"],
    "data_points": [("The book's fourth step is to educate the fixed-mindset persona and take it on the journey with you, rather than suppressing or banning it.", SRC, "Mindset, Ch 8 ('The Journey to a (True) Growth Mindset')", "primary_source", "surprising", "the whole corrective of this film"),
                     ("Its recommended reply is to thank the persona for its input, explain why you want to take the step anyway, and ask whether it can bear with you.", SRC, "Mindset, Ch 8", "primary_source", "expected", "the exact words the film models"),
                     ("The book states the persona was born to protect you and keep you safe, but has developed very limiting ways of doing that.", SRC, "Mindset, Ch 8", "primary_source", "surprising", "the compassion beat, and why banishing it is the wrong move"),
                     ("After a setback it advises letting the persona do its song and dance, then talking to it about what you plan to learn and do next.", SRC, "Mindset, Ch 8", "primary_source", "expected", "what to do on a bad day rather than a brave one")],
    "questions": ["What do I actually say when that voice turns up?", "Why can't I just make it go away?", "Why is it there at all if it only makes things harder?"],
    "misconceptions": [("You should fight the voice and shut it up", "The book says to educate it and bring it along, not to ban it.", "Ch 8"),
                        ("The voice is trying to hurt you", "It was born to protect you and keep you safe; it just learned some very limiting ways of doing it.", "Ch 8")],
    "pain_points": ["Trying to suppress the voice and feeling worse when it comes back louder", "Having no actual sentence to say when it turns up"],
    "angles": [("It Was Trying to Protect You", "contrarian", "The voice isn't your enemy. It was built to keep you safe, badly.", "Reverses the popular framing and makes the voice something she can be kind to.", ["Ch 8"]),
               ("Bring It With You", "narrative", "Don't ban it. Thank it, tell it what you're doing, and ask it to come along.", "Gives her the book's actual instruction rather than the popular one.", ["Ch 8"]),
               ("What To Say", "evergreen", "Here is the actual sentence, ready to use when it turns up.", "Hands her usable words instead of a general attitude.", ["Ch 8"])],
    "kahneman": "The fixed-mindset voice was born to protect you; the instruction is not to banish it but to educate it and take it with you.",
    "excluded": ["The workplace team examples and the adult persona negotiations, which need an adult setting."],
    "concepts": [
        {"id": "c1", "title": "Teach It a New Way", "hook": "Diana, last time we gave that little voice a name. Now here's what to do when it turns up.", "narrative_structure": "story",
         "visual_approach": "The same small grey creature from the previous film, now walking alongside the girl rather than blocking her, eventually carrying a small lantern.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 150,
         "key_points": ["Fighting it makes it louder, not smaller", "It turned up in the first place to keep you safe", "It just learned a very limiting way of doing that", "Thank it, say what you're doing anyway, and ask it to come along", "It ends up walking beside you instead of in front of you"],
         "core_message": "It was never your enemy. It was a frightened little thing trying to keep you safe. Teach it a better way and bring it with you.", "cta": "Next time it turns up, thank it and tell it you're going anyway.", "tone": "Tender, steady, quietly confident.",
         "why_this_works": "It replaces an impossible instruction (silence it) with a doable and kind one, and gives her the exact sentence.", "grounded_in": ["Ch 8"]},
        {"id": "c2", "title": "It Was Trying to Protect You", "hook": "That voice was built to keep you safe. It's just bad at it.", "narrative_structure": "myth_busting",
         "visual_approach": "The small grey creature standing protectively in front of the girl, blocking her path with anxious good intent.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 80,
         "key_points": ["The voice's purpose was protection, not cruelty", "Understanding that makes it possible to work with it instead of against it"],
         "core_message": "It's a frightened thing standing in your way because it doesn't want you hurt.", "cta": "Stop treating it as an enemy.", "tone": "Tender.",
         "why_this_works": "The compassion turn that makes the whole method possible, folded into c1 as its hinge.", "grounded_in": ["Ch 8"]},
        {"id": "c3", "title": "What To Say", "hook": "Here's the actual sentence. Learn this one.", "narrative_structure": "tutorial",
         "visual_approach": "The girl and the creature walking side by side along an open path, neither leading.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 70,
         "key_points": ["Thank it, state what you're doing, invite it along", "Having the words ready matters more than feeling brave"],
         "core_message": "I know this might not work. I'd like to try anyway. Come with me.", "cta": "Use those words the next time it turns up.", "tone": "Practical and warm.",
         "why_this_works": "Turns the principle into a memorised sentence she can use under pressure, folded into c1 as its closing tool.", "grounded_in": ["Ch 8"]}],
    "rationale": "c1 carries the creature from blocking her path to walking beside her; c2 is its compassion hinge and c3 its usable sentence, all three following the same creature from the previous film.",
    "device_short": "the same small grey creature, now walking beside her instead of blocking her",
    "art_direction": "Reused device: the identical small round soft grey creature from the previous film, shown first blocking the path, then walking alongside, finally carrying a small lantern.",
    "device_lock": ("The creature is the identical small round soft grey blob-shaped creature with two simple dot eyes "
                    "and no mouth from the previous film, roughly the size of a cat, drawn flat on cream paper. "
                    "Gentle and slightly worried, never scary, no teeth, no claws, no horns. The lantern is a plain "
                    "small warm lantern. No numerals, no writing, no speech bubbles."),
    "tradeoffs": [{"tradeoff": "Ending with the creature banished versus ending with it walking alongside", "recommendation": "Walking alongside",
                   "quality_impact": "Banishing it would contradict the book's actual instruction and set her up to feel she has failed every time the voice returns, which it will."}],
    "energy_curve": "Warm callback at the opening. Honest through the failed fighting. Tender at the protection reveal. Practical at the sentence. Settled and hopeful at the close of the Mindset half.",
    "sample_section": "s9", "human_note": "Section s9 is the protection reveal. This is the emotional centre of the whole Mindset half. Slow and tender.",
    "pause_beats": [{"section": "s5", "purpose": "She sits with the fact that fighting it hasn't worked"}, {"section": "s10", "purpose": "She takes in that it was trying to protect her"}, {"section": "s13", "purpose": "She practises the actual sentence"}],
    "grounded_in": {"s1_to_s4": "Ch 8, why suppression fails", "s5_to_s8": "Ch 8, don't ban it, let it speak", "s9_to_s11": "Ch 8, it was born to protect you", "s12_to_s15": "Ch 8 step 4, educate it and take it with you"},
    "sections": [
        ("s1", "Setup", "Diana, last time we gave that little voice a name. Now here's what to do when it turns up.", "Diana, last time we gave that little voice a name. <break time=\"0.4s\"/> Now here's what to do when it turns up.", 1.4, "measured", "warm", ["turns up"], "Direct callback, warm."),
        ("s2", "The obvious idea", "The obvious idea is to fight it. Tell it to be quiet. Push it away.", "The obvious idea is to fight it. <break time=\"0.4s\"/> Tell it to be quiet. <break time=\"0.4s\"/> Push it away.", 1.4, "measured", "steady", ["push it away"], "State the popular advice neutrally."),
        ("s3", "Why that fails", "I've tried that for about thirty years. It doesn't work. It just comes back louder, and then you're tired as well.", "I've tried that for about thirty years. <break time=\"0.4s\"/> It doesn't work. <break time=\"0.5s\"/> It just comes back louder, <break time=\"0.3s\"/> and then you're tired as well.", 1.4, "measured", "wry", ["comes back louder"], "Dry, honest, a little self-deprecating."),
        ("s4", "The book disagrees", "So the book says something I didn't expect. Don't ban it. Don't argue with it at all.", "So the book says something I didn't expect. <break time=\"0.5s\"/> Don't ban it. <break time=\"0.4s\"/> Don't argue with it at all.", 1.4, "measured", "curious", ["don't ban it"], "Genuine surprise."),
        ("s5", "Let it speak", "Let it say its piece. Let it do its whole song and dance. And then wait for it to settle.", "Let it say its piece. <break time=\"0.4s\"/> Let it do its whole song and dance. <break time=\"0.4s\"/> And then wait for it to settle. <break time=\"2.5s\"/>", 2.5, "slow", "steady", ["settle"], "Pause beat one. Model the patience."),
        ("s6", "It runs out", "Because it always does settle. It's a small thing. It hasn't got that much to say.", "Because it always does settle. <break time=\"0.4s\"/> It's a small thing. <break time=\"0.4s\"/> It hasn't got that much to say.", 1.4, "measured", "warm", ["small thing"], "Reassuring and slightly light."),
        ("s7", "Then look at it", "And when it's quiet, have a proper look at it. Not angry. Just looking.", "And when it's quiet, have a proper look at it. <break time=\"0.4s\"/> Not angry. <break time=\"0.4s\"/> Just looking.", 1.4, "measured", "gentle", ["just looking"], "Soft."),
        ("s8", "What you see", "It's not a monster, Diana. It's small, and it's worried, and it's standing in your way.", "It's not a monster, Diana. <break time=\"0.4s\"/> It's small, and it's worried, <break time=\"0.3s\"/> and it's standing in your way.", 1.4, "measured", "tender", ["worried"], "Set up the reveal."),
        ("s9", "The reveal", "Because here's the thing I want you to really hear. It turned up in the first place to protect you. It didn't want you to get hurt.", "Because here's the thing I want you to really hear. <break time=\"0.5s\"/> It turned up in the first place to protect you. <break time=\"0.5s\"/> It didn't want you to get hurt.", 1.4, "slow", "tender", ["to protect you"], "The emotional centre of the whole Mindset half. Slow and warm."),
        ("s10", "It's just bad at it", "It's just learned a rubbish way of doing it. Keeping you still and safe and small.", "It's just learned a rubbish way of doing it. <break time=\"0.5s\"/> Keeping you still and safe and small. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["safe and small"], "Pause beat two. Let the sadness of that land gently."),
        ("s11", "So teach it", "So you don't banish it. You teach it. You show it there's a better way to keep you safe.", "So you don't banish it. <break time=\"0.4s\"/> You teach it. <break time=\"0.4s\"/> You show it there's a better way to keep you safe.", 1.4, "measured", "warm", ["you teach it"], "Firm and kind."),
        ("s12", "How to teach it", "And you do that by taking it with you. Not leaving it behind. Taking it.", "And you do that by taking it with you. <break time=\"0.4s\"/> Not leaving it behind. <break time=\"0.4s\"/> Taking it.", 1.4, "measured", "steady", ["taking it"], "The core instruction."),
        ("s13", "The sentence", "Here are the words. Thank you. I know this might not work. I'd like to try anyway. Come with me.", "Here are the words. <break time=\"0.5s\"/> Thank you. <break time=\"0.4s\"/> I know this might not work. <break time=\"0.4s\"/> I'd like to try anyway. <break time=\"0.4s\"/> Come with me. <break time=\"2.5s\"/>", 2.5, "slow", "warm", ["come with me"], "Pause beat three. Say it exactly as she should say it."),
        ("s14", "What happens", "And a strange thing happens over the years. It stops standing in front of you. It starts walking beside you.", "And a strange thing happens over the years. <break time=\"0.5s\"/> It stops standing in front of you. <break time=\"0.4s\"/> It starts walking beside you.", 1.4, "measured", "warm", ["beside you"], "Warm and hopeful."),
        ("s15", "Landing", "You've got everything you need now, Diana. A door still being built, a word called yet, and a small worried friend who walks beside you. That'll do.", "You've got everything you need now, Diana. <break time=\"0.5s\"/> A door still being built, <break time=\"0.3s\"/> a word called yet, <break time=\"0.3s\"/> and a small worried friend who walks beside you. <break time=\"0.5s\"/> That'll do.", 0.0, "slow", "tender", ["that'll do"], "Closes the whole Mindset half. Callbacks to films 1 and 2. Unhurried, proud, warm."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl stands warmly attentive, ready and calm, a small smile of recognition."),
        ("sc2", "s2", "NONE", "The small grey creature being pushed back by an unseen hand, only the hand and forearm visible, no face and no body."),
        ("sc3", "s3", "NONE", "The small grey creature returned and sitting slightly larger than before, calm and unbothered."),
        ("sc4", "s4", "DIANA", "The girl looks curious and surprised, caught by an unexpected idea."),
        ("sc5", "s5", "NONE", "The small grey creature mid-fuss, drawn with small motion lines suggesting it is saying its piece."),
        ("sc6", "s6", "NONE", "The small grey creature now settled and quiet, sitting still on the cream page."),
        ("sc7", "s7", "DIANA", "The girl looks at something small with gentle steady attention, calm and unafraid."),
        ("sc8", "s8", "NONE", "The small grey creature standing directly in a plain path, blocking it, looking anxious rather than threatening."),
        ("sc9", "s9", "NONE", "The small grey creature standing protectively in front of a plain figure silhouette, arms slightly spread as if shielding them."),
        ("sc10", "s10", "DIANA", "The girl's expression softens with understanding, quiet and moved, a little tender."),
        ("sc11", "s11", "DIANA", "The girl crouches slightly, looking down kindly at something small, gentle and patient."),
        ("sc12", "s12", "NONE", "The small grey creature turning to face the same direction as a plain path, no longer blocking it."),
        ("sc13", "s13", "DIANA", "The girl speaks gently and clearly to something small, warm and steady."),
        ("sc14", "s14", "NONE", "A plain figure silhouette and the small grey creature walking side by side along an open path, neither in front."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s9", "NONE", "A close view of the small grey creature standing protectively, its posture clearly worried and well-meaning."),
        ("sc17", "s14", "NONE", "The figure and the creature walking together along the open path, warmly lit, unhurried and companionable."),
        ("sc18", "s15", "NONE", "The small grey creature walking beside a plain figure into warm evening light, carrying a small warm lantern, calm and settled."),
    ],
    "heroes": {"sc9", "sc14", "sc16", "sc18"}, "wides": {"sc14", "sc17", "sc18"},
}
FILM13["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc4", "sc7", "sc10", "sc11", "sc13", "sc15"}),
    "NOICON": (G.NOICON, {"sc1", "sc4", "sc7", "sc10", "sc11", "sc13", "sc15"}),
    "SHOES": (SHOES, {"sc1", "sc4", "sc7", "sc10", "sc11", "sc13", "sc15"}),
    "CREATURE": (("The creature is the identical small round soft grey blob-shaped creature with two simple dot eyes "
                  "and no mouth used in the previous film, roughly the size of a cat, drawn flat on cream paper. "
                  "Gentle and slightly worried, never scary, no teeth, no claws, no horns, no shadow-monster "
                  "styling. Plain figure silhouettes have no facial features and no clothing detail. The path is a "
                  "plain simple ground-level path with no scenery. The lantern is one plain small warm lantern. "
                  "No numerals, no writing, no speech bubbles."),
                 {"sc2", "sc3", "sc5", "sc6", "sc8", "sc9", "sc12", "sc14", "sc16", "sc17", "sc18"}),
}

if __name__ == "__main__":
    G_FILMS = {"m10": FILM10, "m11": FILM11, "m12": FILM12, "m13": FILM13}
    args = sys.argv[1:]
    slugs = [a for a in args if a in G_FILMS] or list(G_FILMS)
    for key in slugs:
        f = G_FILMS[key]
        if "init" in args:
            G.init(f)
        if "build" in args:
            G.build(f)
        if "sheet" in args:
            G.sheet(f)
