"""Mindset series, films 2-5 of 25: Yet / Mistakes Grow Your Brain / Effort / No Natural."""
import sys
import filmgen as G
from mindset_a import base, SRC

# ---------------------------------------------------------------- FILM 2
FILM2 = {**base(2, "diana-mindset-yet", "DianaTheWordYet", "The Most Powerful Word Is Yet", "Ch 1-2"),
    "topic": "The word 'yet' as a growth-mindset device, told as Dad teaching Diana one small word that changes a whole sentence",
    "summary": ("Film 2. Chapters 1 and 2. Dweck's own public description of this book's central finding is often "
                "condensed into a single word: adding 'yet' to a sentence turns a verdict into a status report. "
                "'I can't do this' is a locked door. 'I can't do this yet' is a door with a hinge on it. Grounded "
                "in the book's account of how mindsets change the meaning of failure."),
    "existing": [{"title": "Classroom 'growth mindset' word walls", "url": SRC, "source": "school material",
                  "angle": "Use growth mindset words", "what_it_covers": "Lists the word without explaining why one word changes the whole sentence"},
                 {"title": "Generic positivity content for children", "url": SRC, "source": "web", "angle": "Stay positive",
                  "what_it_covers": "General encouragement, not this specific mechanism"},
                 {"title": "Mindsetworks.com classroom resources", "url": SRC, "source": "author's organisation",
                  "angle": "Teacher-facing framing", "what_it_covers": "Aimed at adults implementing it, not spoken to a child directly"}],
    "saturated": ["Word-wall posters that name the trick without explaining it"],
    "gaps": ["Showing the sentence physically change shape when the word is added", "A father modelling it on his own sentence, not just hers"],
    "data_points": [
        ("A sentence that ends in failure is a closed verdict; the same sentence with 'yet' added becomes a status report on a journey still underway.", SRC, "Mindset, Ch 1-2", "secondary_source", "expected", "the hinge-word device"),
        ("Mindsets change the meaning of failure itself: a fixed mindset treats it as identity, a growth mindset treats it as information.", SRC, "Mindset, Ch 2 (TOC: 'Mindsets Change the Meaning of Failure')", "secondary_source", "expected", "why 'yet' works at all"),
        ("The finding is one of Dweck's most consistently repeated public explanations of her own research across interviews and talks.", SRC, "Public description of Mindset's findings", "secondary_source", "expected", "justifies teaching it as the book's own shorthand")],
    "questions": ["Why does adding one word change how a sentence feels?", "Is 'I can't do this' actually true?", "What's the difference between not yet and never?"],
    "misconceptions": [("'I can't' and 'I can't yet' mean the same thing", "One is a locked door, the other has a hinge.", "Ch 1-2"),
                        ("Yet is just a nicer way of saying the same thing", "It changes what the sentence claims: never versus not yet.", "Ch 2")],
    "pain_points": ["Declaring 'I can't' after one try and stopping there"],
    "angles": [("The Sentence With a Hinge", "narrative", "Watch one word turn a wall into a door.", "Physical, visual, and needs no vocabulary at all.", ["Ch 1-2"]),
               ("Dad's Own Yet", "evergreen", "I say I can't yet, about things too.", "Makes the tool something modelled, not assigned.", ["Ch 1-2"]),
               ("Never Versus Not Yet", "contrarian", "They sound similar. They are opposites.", "The precise distinction the whole trick rests on.", ["Ch 2"])],
    "kahneman": "Adding 'yet' turns a fixed verdict about yourself into an honest status report on something still in progress.",
    "excluded": ["Detailed classroom-study statistics on the word's measured effect, which need adult framing."],
    "concepts": [
        {"id": "c1", "title": "The Most Powerful Word Is Yet", "hook": "Diana, watch what happens when I add one small word to a sentence.",
         "narrative_structure": "story", "visual_approach": "A single word appearing at the end of a sentence-shaped wall, turning it into a gate with a hinge.",
         "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 145,
         "key_points": ["I can't do this is a locked wall", "I can't do this yet has a hinge", "Yet doesn't promise it will happen, it just leaves the door open", "It's the same for Dad", "You can add it right now, out loud"],
         "core_message": "Yet doesn't make the wall disappear. It just puts a hinge on it.", "cta": "Say your can't out loud, then add the word yet to it.", "tone": "Playful, then genuinely useful.",
         "why_this_works": "It's a tool she can use in the next five minutes, demonstrated on Dad's own sentence first.", "grounded_in": ["Ch 1-2"]},
        {"id": "c2", "title": "Never Versus Not Yet", "hook": "Those two sound almost the same. They are opposites.",
         "narrative_structure": "comparison", "visual_approach": "A sealed wall beside a wall with one visible hinge.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 90,
         "key_points": ["Never claims to know the future", "Not yet admits it doesn't"], "core_message": "One is a guess dressed as a fact.", "cta": "Catch yourself saying never.", "tone": "Curious",
         "why_this_works": "The precise distinction underneath the whole trick, folded into c1 as its hinge moment.", "grounded_in": ["Ch 2"]},
        {"id": "c3", "title": "Dad's Sentence", "hook": "I have a can't too.", "narrative_structure": "story", "visual_approach": "An adult-sized wall beside the same small hinge.",
         "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 80,
         "key_points": ["Grown-ups use this too", "It's a lifelong tool, not a school trick"], "core_message": "Yet works at every age.", "cta": "Notice Dad using it.", "tone": "Warm",
         "why_this_works": "Models the tool rather than only assigning it, folded into c1 as its personal turn.", "grounded_in": ["Ch 1-2"]}],
    "rationale": "c1 carries the whole demonstration; c2 and c3 are the hinge-moment and the modelling beat folded inside it, since the trick is too small to sustain three separate films.",
    "device_short": "a wall-shaped sentence that grows a hinge when the word yet is added",
    "art_direction": "New device: a plain stone wall shaped like a sentence, sealed until a small wooden hinge appears at one edge and the wall becomes a gate.",
    "device_lock": "A flat rectangular stone wall on cream paper, sealed and plain. The same wall with one small wooden hinge fixed to its right edge, now clearly a gate that could open. No numerals, no letters, no actual written words anywhere.",
    "tradeoffs": [{"tradeoff": "Writing the actual word 'yet' on screen versus showing only the hinge", "recommendation": "Show only the hinge, never write the word",
                   "quality_impact": "No lettering may appear in any illustration; the hinge carries the idea without needing text on screen."}],
    "energy_curve": "Playful at the demonstration. Curious at the hinge appearing. Warm at Dad's own sentence. Bright and useful at the close.",
    "sample_section": "s7", "human_note": "Section s7 is the actual trick. Say it like you're handing her something, not teaching her something.",
    "pause_beats": [{"section": "s3", "purpose": "She watches the hinge appear and takes it in"}, {"section": "s9", "purpose": "She thinks of her own can't"}, {"section": "s13", "purpose": "She says it out loud with yet added"}],
    "grounded_in": {"s1_to_s4": "Ch 1-2, the wall-to-gate demonstration", "s5_to_s8": "Ch 2, never versus not yet", "s9_to_s11": "Ch 1-2 applied to her own can'ts", "s12_to_s15": "Ch 1-2 corrective plus Dad's own example"},
    "sections": [
        ("s1", "Setup", "Diana, watch what happens when I add one small word to a sentence.", 'Diana, watch what happens when I add one small word to a sentence.', 1.4, "measured", "playful", ["one small word"], "Light, inviting her to watch closely."),
        ("s2", "The sentence", "I can't do this. Say that out loud. Feels pretty final, doesn't it.", "I can't do this. <break time=\"0.4s\"/> Say that out loud. <break time=\"0.5s\"/> Feels pretty final, doesn't it.", 1.4, "measured", "steady", ["final"], "Let it land flat and closed."),
        ("s3", "The hinge appears", "Now. I can't do this... yet. Did you feel that? A little hinge just appeared on the wall.", "Now. <break time=\"0.4s\"/> I can't do this... <break time=\"0.5s\"/> yet. <break time=\"0.5s\"/> Did you feel that? <break time=\"0.4s\"/> A little hinge just appeared on the wall. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["hinge"], "Pause beat one. Let the shift actually register."),
        ("s4", "Same wall", "It's the exact same wall. Nothing about it got easier. But now it has a way through.", "It's the exact same wall. <break time=\"0.4s\"/> Nothing about it got easier. <break time=\"0.4s\"/> But now it has a way through.", 1.4, "measured", "steady", ["way through"], "Be precise: nothing got easier."),
        ("s5", "Not a promise", "Yet doesn't promise you'll get it. It just says the door isn't sealed shut.", "Yet doesn't promise you'll get it. <break time=\"0.5s\"/> It just says the door isn't sealed shut.", 1.4, "measured", "gentle", ["not sealed"], "Guard against overclaiming."),
        ("s6", "Never versus yet", "Never and not yet sound almost the same. They are opposites. One knows the future. One admits it doesn't.", "Never and not yet sound almost the same. <break time=\"0.4s\"/> They are opposites. <break time=\"0.5s\"/> One knows the future. <break time=\"0.4s\"/> One admits it doesn't.", 1.4, "slow", "curious", ["opposites"], "The hinge of the film, spoken slowly."),
        ("s7", "The trick itself", "So here's your second trick in this set. Every time you hear yourself say can't, add the word yet to the end.", "So here's your second trick in this set. <break time=\"0.5s\"/> Every time you hear yourself say can't, <break time=\"0.4s\"/> add the word yet to the end.", 1.4, "measured", "encouraging", ["add the word"], "This is the whole point. Say it clearly."),
        ("s8", "It's for me too", "I do this too, Diana. I still have things I say I can't do yet.", "I do this too, Diana. <break time=\"0.4s\"/> I still have things I say I can't do yet.", 1.4, "measured", "warm", ["still"], "Genuine, not a performance of humility."),
        ("s9", "Her turn", "So think of one thing right now. A real one. Something you'd normally say I can't do.", "So think of one thing right now. <break time=\"0.4s\"/> A real one. <break time=\"0.5s\"/> Something you'd normally say I can't do. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["real one"], "Pause beat two. She needs an actual example."),
        ("s10", "Watch it change", "Now say it again. With yet on the end. Notice what happens to how it feels in your chest.", "Now say it again. <break time=\"0.4s\"/> With yet on the end. <break time=\"0.5s\"/> Notice what happens to how it feels in your chest.", 1.4, "measured", "curious", ["your chest"], "Bring it into the body, not just the head."),
        ("s11", "The wall doesn't vanish", "The hard thing is still hard. That part didn't change. Only the door did.", "The hard thing is still hard. <break time=\"0.4s\"/> That part didn't change. <break time=\"0.4s\"/> Only the door did.", 1.4, "measured", "steady", ["only the door"], "Honest, not magical thinking."),
        ("s12", "Small word, big turn", "One tiny word. That's all it takes to turn a full stop into a comma.", "One tiny word. <break time=\"0.4s\"/> That's all it takes to turn a full stop into a comma.", 1.4, "slow", "warm", ["comma"], "A gentle image to end the explanation on."),
        ("s13", "Say it now", "Go on. Say your can't out loud, with yet on the end. I'm listening.", "Go on. <break time=\"0.4s\"/> Say your can't out loud, with yet on the end. <break time=\"0.5s\"/> I'm listening. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["I'm listening"], "Pause beat three. Genuinely wait for it."),
        ("s14", "Carry it", "Carry that word with you tomorrow. It weighs nothing and it opens almost everything.", "Carry that word with you tomorrow. <break time=\"0.5s\"/> It weighs nothing and it opens almost everything.", 1.4, "measured", "encouraging", ["opens"], "Bright, forward-looking."),
        ("s15", "Landing", "You're not stuck, Diana. You're just not there yet. And I'll be right here while you get there.", "You're not stuck, Diana. <break time=\"0.5s\"/> You're just not there yet. <break time=\"0.5s\"/> And I'll be right here while you get there.", 0.0, "slow", "tender", ["right here"], "Warm, personal, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl looks at the viewer with curious anticipation, waiting to see something."),
        ("sc2", "s2", "NONE", "A plain flat stone wall shaped like a low rectangular block, sealed and closed, standing alone on the page."),
        ("sc3", "s3", "NONE", "The same stone wall now with one small wooden hinge fixed to its right edge, subtly ajar."),
        ("sc4", "s4", "NONE", "The hinged wall standing slightly open at its hinge, a thin gap of light showing through."),
        ("sc5", "s5", "NONE", "A close view of the small wooden hinge alone, plain and unremarkable."),
        ("sc6", "s6", "NONE", "Two plain walls side by side: one fully sealed, one with a hinge, otherwise identical."),
        ("sc7", "s7", "DIANA", "The girl's face lit with quiet recognition, as if she has just been handed something useful."),
        ("sc8", "s8", "NONE", "A larger, adult-sized version of the hinged wall standing beside a small one, same style."),
        ("sc9", "s9", "DIANA", "The girl sits thinking, one hand resting on her chest, genuinely working something out."),
        ("sc10", "s10", "NONE", "The stone wall's hinge glowing softly warm, as if something inside has just shifted."),
        ("sc11", "s11", "NONE", "The hinged wall standing firm and still hard-looking, its surface rough and solid despite the open hinge."),
        ("sc12", "s12", "NONE", "One small dot at the end of a plain flat line, transforming into a small curl at the same spot."),
        ("sc13", "s13", "DIANA", "The girl stands with her chin lifted, about to speak, open and ready."),
        ("sc14", "s14", "NONE", "A single small wooden hinge held loosely in an open palm. Only the hand and forearm are visible, no face and no body."),
        ("sc15", "s15", "DIANA", "The girl stands calm and settled in warm evening light, at ease."),
        ("sc16", "s4", "NONE", "The hinged wall standing ajar with warm light spilling through the gap onto the cream paper."),
        ("sc17", "s6", "NONE", "The sealed wall alone, plain and closed, no hinge visible anywhere on it."),
        ("sc18", "s15", "DIANA", "The girl and a warm glow of light together, calm, unhurried, at the end of the day."),
    ],
    "heroes": {"sc3", "sc16", "sc18"}, "wides": {"sc6"},
}
FILM2["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc5", "sc7", "sc8", "sc9", "sc10", "sc12", "sc13", "sc14", "sc15", "sc18"}),
    "NOICON": (G.NOICON, {"sc1", "sc7", "sc9", "sc12", "sc13", "sc14", "sc15", "sc18"}),
    "WALL": (("The wall is a plain flat rectangular stone block drawn simply from the side on cream paper, no "
              "landscape, no room, no scenery. The hinge is one small plain wooden fitting. Absolutely no letters, "
              "words or writing appear anywhere in any scene."),
             {"sc2", "sc3", "sc4", "sc6", "sc8", "sc11", "sc16", "sc17"}),
}

# ---------------------------------------------------------------- FILM 3
FILM3 = {**base(3, "diana-mindset-mistakes", "DianaMistakesGrowBrains", "Mistakes Are How Your Brain Grows", "Ch 2"),
    "topic": "Mistakes as brain growth rather than proof of failure, from Chapter 2's discussion of what mindsets do to the meaning of failure",
    "summary": ("Film 3. Chapter 2, 'Mindsets Change the Meaning of Failure.' In a growth mindset, a mistake is not "
                "a verdict on who you are, it is the exact moment learning happens. Grounded in the book's own "
                "TOC-confirmed section title, told through a tangled knot that becomes stronger the more it is "
                "worked through rather than avoided."),
    "existing": [{"title": "Encourage-resilience children's material", "url": SRC, "source": "web", "angle": "Don't give up",
                  "what_it_covers": "Tells her to keep going without explaining what a mistake is actually doing"},
                 {"title": "School posters on 'growth mindset'", "url": SRC, "source": "classroom material", "angle": "Mistakes help you learn",
                  "what_it_covers": "States the conclusion as a slogan, not as something she can feel happening"},
                 {"title": "Fail-fast tech-culture slogans", "url": SRC, "source": "web", "angle": "Failure is a badge of honour",
                  "what_it_covers": "Celebrates failure in the abstract without showing what to actually do with one specific mistake"}],
    "saturated": ["Generic don't-give-up resilience messaging"],
    "gaps": ["Showing what actually happens in the moment of a mistake, not just asserting it's good"],
    "data_points": [("In a growth mindset, mistakes are treated as information about what to try next, not as a verdict on ability.", SRC, "Mindset, Ch 2", "secondary_source", "expected", "the knot device"),
                     ("The chapter's own heading names this directly: mindsets change the meaning of failure itself.", SRC, "Mindset, Ch 2 (TOC)", "primary_source", "expected", "grounds the claim in the book's own structure"),
                     ("People with a fixed mindset are more likely to hide mistakes; people with a growth mindset are more likely to examine them.", SRC, "Mindset, Ch 2", "secondary_source", "expected", "the hiding-versus-examining contrast")],
    "questions": ["Why does getting something wrong feel so bad?", "Is a mistake proof I'm not good at something?", "What should I actually do right after I get something wrong?"],
    "misconceptions": [("A mistake proves you're bad at something", "A mistake is information about this attempt, not a verdict on you.", "Ch 2"),
                        ("Good at something means never getting it wrong", "Getting things wrong is what the learning is made of.", "Ch 2")],
    "pain_points": ["Hiding a wrong answer instead of looking at it", "Feeling a mistake as shame rather than as information"],
    "angles": [("The Knot That Gets Stronger", "narrative", "A tangled knot worked through, not avoided, ends up stronger where it was tangled.", "A physical object she has handled herself, no vocabulary needed.", ["Ch 2"]),
               ("Hide It or Look At It", "contrarian", "Two children, same mistake, different next move.", "The book's own hiding-versus-examining contrast made concrete.", ["Ch 2"]),
               ("The Moment It Actually Happens", "evergreen", "Growth isn't a slogan, it's a specific second.", "Shows the mechanism instead of asserting the conclusion.", ["Ch 2"])],
    "kahneman": "A mistake examined rather than hidden is the specific moment new learning happens.",
    "excluded": ["The detailed school-achievement statistics from Chapter 3, saved for a later film."],
    "concepts": [
        {"id": "c1", "title": "Mistakes Are How Your Brain Grows", "hook": "Diana, I want you to look really closely at a knot with me.", "narrative_structure": "story",
         "visual_approach": "A tangled length of rope worked through by hand until the once-tangled part becomes the strongest, most textured section of the whole rope.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 145,
         "key_points": ["A mistake is a tangle, not a verdict", "Working through it, not avoiding it, is what changes it", "The worked-through spot becomes the strongest part of the rope", "Hiding a mistake keeps it tangled", "Looking closely at it is the actual growing"],
         "core_message": "The knot doesn't disappear by ignoring it. It gets stronger exactly where you worked it through.", "cta": "Next time you get something wrong, look at it instead of hiding it.", "tone": "Warm, patient, hands-on.",
         "why_this_works": "It gives her a physical, felt image for something usually only said as encouragement.", "grounded_in": ["Ch 2"]},
        {"id": "c2", "title": "Hide It or Look At It", "hook": "Two children make the same mistake. Watch what each one does next.", "narrative_structure": "comparison",
         "visual_approach": "One knot pushed under a cloth, one knot held up to the light.", "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old",
         "target_platform": "generic", "target_duration_seconds": 90, "key_points": ["Hiding keeps it tangled forever", "Looking is uncomfortable but it's the only way through"],
         "core_message": "You can't untangle what you won't look at.", "cta": "Look at the mistake before you fix it.", "tone": "Honest", "why_this_works": "The book's own contrast, folded into c1 as its middle beat.", "grounded_in": ["Ch 2"]},
        {"id": "c3", "title": "The Strongest Part of the Rope", "hook": "Feel where the rope was once tangled. That's the strongest bit now.", "narrative_structure": "analogy",
         "visual_approach": "A close view of the worked-through section of rope, visibly denser and stronger than the rest.", "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old",
         "target_platform": "generic", "target_duration_seconds": 80, "key_points": ["Struggle leaves a mark, and the mark is strength", "The mended spot is stronger than the rope ever was before it tangled"], "core_message": "The mended spot is the strong spot.", "cta": "Notice your own mended spots.",
         "tone": "Tender", "why_this_works": "The physical payoff of the whole idea, folded into c1 as its closing image.", "grounded_in": ["Ch 2"]}],
    "rationale": "c1 carries the full arc from tangle to strength; c2 and c3 are its middle contrast and its closing evidence, since all three share one continuous rope image.",
    "device_short": "a tangled length of rope that becomes strongest exactly where it was worked through",
    "art_direction": "New device: a length of plain warm rope, shown tangled, then being worked through by hand, ending visibly denser and stronger at the once-tangled point.",
    "device_lock": "One continuous length of plain twisted rope in warm ochre tones on cream paper. Tangled sections are looser and looped; worked-through sections are denser, tighter, and slightly raised. No numerals.",
    "tradeoffs": [{"tradeoff": "Showing the mistake as something dramatic versus something small and everyday", "recommendation": "Small and everyday",
                   "quality_impact": "A dramatic failure would need a specific real scenario risking comparison to something she's actually experienced; a plain rope keeps the idea general and safe to apply anywhere."}],
    "energy_curve": "Gentle and hands-on from the opening. Curious through the working-through. Honest at hide-or-look. Tender at the strong spot. Warm at the close.",
    "sample_section": "s9", "human_note": "Section s9 is the honesty beat about hiding mistakes. Keep it warm, never scolding.",
    "pause_beats": [{"section": "s4", "purpose": "She notices the tangle up close before it's worked through"}, {"section": "s10", "purpose": "She thinks of a mistake she hid rather than looked at"}, {"section": "s13", "purpose": "She decides what she'll do with the next one"}],
    "grounded_in": {"s1_to_s4": "Ch 2, the knot introduced", "s5_to_s8": "Ch 2, working through versus avoiding", "s9_to_s11": "Ch 2, hiding versus examining", "s12_to_s15": "Ch 2 corrective, the strong spot"},
    "sections": [
        ("s1", "Setup", "Diana, I want you to look really closely at a knot with me.", "Diana, I want you to look really closely at a knot with me.", 1.4, "measured", "warm", ["knot"], "Inviting, hands-on tone."),
        ("s2", "The tangle", "See how tangled this bit is. Messy. Annoying. You'd want to just leave it alone, wouldn't you.", "See how tangled this bit is. <break time=\"0.4s\"/> Messy. <break time=\"0.3s\"/> Annoying. <break time=\"0.4s\"/> You'd want to just leave it alone, wouldn't you.", 1.4, "measured", "curious", ["tangled"], "Genuinely acknowledge the discomfort."),
        ("s3", "Working it through", "But watch what happens if you actually work it through, instead of pulling away from it.", "But watch what happens if you actually work it through, <break time=\"0.4s\"/> instead of pulling away from it.", 1.4, "measured", "steady", ["work it through"], "Slow, deliberate."),
        ("s4", "Close look", "Look closely right at the spot where it was tangled.", "Look closely right at the spot where it was tangled. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["closely"], "Pause beat one. Genuine looking time."),
        ("s5", "The point", "That mistake, right there, is exactly where your brain is doing its hardest work.", "That mistake, right there, <break time=\"0.4s\"/> is exactly where your brain is doing its hardest work.", 1.4, "measured", "warm", ["hardest work"], "The hinge, said plainly."),
        ("s6", "Not a verdict", "It doesn't mean you're bad at this. It means this exact bit needs your attention right now.", "It doesn't mean you're bad at this. <break time=\"0.5s\"/> It means this exact bit needs your attention right now.", 1.4, "measured", "gentle", ["attention"], "Direct correction of the misconception."),
        ("s7", "Two children", "Imagine two kids make the exact same mistake. One shoves it under a cloth so nobody sees. One holds it up to the light.", "Imagine two kids make the exact same mistake. <break time=\"0.4s\"/> One shoves it under a cloth so nobody sees. <break time=\"0.5s\"/> One holds it up to the light.", 1.4, "measured", "curious", ["light"], "Set the contrast clearly."),
        ("s8", "Which one grows", "Only one of those knots is ever going to come untangled. Guess which.", "Only one of those knots is ever going to come untangled. <break time=\"0.4s\"/> Guess which.", 1.4, "measured", "wry", ["guess"], "A little dry, inviting her answer."),
        ("s9", "Hiding it", "Hiding a mistake feels safer. But the tangle just stays a tangle, forever, under the cloth.", "Hiding a mistake feels safer. <break time=\"0.5s\"/> But the tangle just stays a tangle, forever, under the cloth.", 1.4, "measured", "tender", ["forever"], "Kind, not scolding. This is the honesty beat."),
        ("s10", "Her own knot", "Think of a mistake you've hidden rather than looked at.", "Think of a mistake you've hidden rather than looked at. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["hidden"], "Pause beat two. No pressure to say it aloud."),
        ("s11", "It's alright", "That's alright. Everybody has a hidden one. The only question is what you do with the next one.", "That's alright. <break time=\"0.5s\"/> Everybody has a hidden one. <break time=\"0.4s\"/> The only question is what you do with the next one.", 1.4, "measured", "warm", ["next one"], "Release the shame, redirect forward."),
        ("s12", "The strong spot", "Feel this rope now. Right where it was once tangled is the strongest part of the whole thing.", "Feel this rope now. <break time=\"0.4s\"/> Right where it was once tangled is the strongest part of the whole thing.", 1.4, "slow", "tender", ["strongest"], "Land the physical image."),
        ("s13", "Your move", "So next time you get something wrong, do this. Look at it. Don't hide it. Not straight away, just look.", "So next time you get something wrong, do this. <break time=\"0.5s\"/> Look at it. <break time=\"0.4s\"/> Not straight away, <break time=\"0.3s\"/> just look. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["just look"], "Pause beat three. Simple, doable instruction."),
        ("s14", "It won't feel nice", "It won't feel nice straight away. That's alright. Neither does untangling a knot.", "It won't feel nice straight away. <break time=\"0.5s\"/> That's alright. <break time=\"0.4s\"/> Neither does untangling a knot.", 1.4, "measured", "steady", ["alright"], "Honest about the discomfort."),
        ("s15", "Landing", "Your brain is growing exactly where it's tangled, Diana. I'm proud of you for working through it, not around it.", "Your brain is growing exactly where it's tangled, Diana. <break time=\"0.5s\"/> I'm proud of you for working through it, <break time=\"0.4s\"/> not around it.", 0.0, "slow", "tender", ["proud"], "Warm, specific, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl holds a length of rope up between her two hands, looking at it with focused curiosity."),
        ("sc2", "s2", "NONE", "A length of plain warm rope with one messy, loosely tangled section in the middle."),
        ("sc3", "s3", "NONE", "The same rope with a pair of hands beginning to gently work the tangled section through, loosening it deliberately."),
        ("sc4", "s4", "NONE", "A close view of the tangled section of rope, textured and detailed, nothing else in frame."),
        ("sc5", "s5", "DIANA", "The girl leans in close, focused and absorbed, working the rope with her fingers."),
        ("sc6", "s6", "DIANA", "The girl looks up with a reassured, gentle expression, no longer worried."),
        ("sc7", "s7", "NONE", "Two identical short lengths of rope side by side, each with the same small tangle."),
        ("sc8", "s8", "NONE", "One rope's tangle is pushed under a small plain cloth; the other rope's tangle sits in open light."),
        ("sc9", "s9", "NONE", "A small plain cloth draped loosely over a lump, hiding what's beneath it."),
        ("sc10", "s10", "DIANA", "The girl sits quietly, thinking, hands resting in her lap, genuinely reflective."),
        ("sc11", "s11", "DIANA", "The girl looks calm and unburdened, a small gentle smile, at peace."),
        ("sc12", "s12", "NONE", "A close view of a rope section that is visibly denser, thicker and more tightly woven than the rest of the rope around it."),
        ("sc13", "s13", "DIANA", "The girl holds a small tangled rope thoughtfully in both hands, examining it calmly rather than flinching from it."),
        ("sc14", "s14", "NONE", "The tangled rope section mid-work, hands still gently working it through."),
        ("sc15", "s15", "DIANA", "The girl sits content in warm evening light, the length of rope now smooth and resting beside her."),
        ("sc16", "s5", "NONE", "The rope's once-tangled section, now smoother, warmly lit, the working-through nearly complete."),
        ("sc17", "s12", "NONE", "The full length of rope laid out, one section visibly denser and stronger than the rest along its whole length."),
        ("sc18", "s15", "NONE", "The smooth, fully worked-through rope resting in a gentle coil, warm and settled in soft light."),
    ],
    "heroes": {"sc12", "sc17", "sc18"}, "wides": {"sc17"},
}
FILM3["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc5", "sc6", "sc9", "sc10", "sc11", "sc13", "sc14", "sc15"}),
    "NOICON": (G.NOICON, {"sc1", "sc5", "sc6", "sc9", "sc10", "sc11", "sc13", "sc15"}),
    "ROPE": (("The rope is one continuous plain twisted rope in warm ochre and tan tones, drawn simply and physically "
              "on cream paper, no other objects, no scenery. Tangled sections are looser and looped; worked-through "
              "sections are denser and slightly raised. No numerals, no writing."),
             {"sc2", "sc3", "sc4", "sc7", "sc8", "sc12", "sc14", "sc16", "sc17", "sc18"}),
}

# ---------------------------------------------------------------- FILM 4
FILM4 = {**base(4, "diana-mindset-effort", "DianaEffortRoots", "Why Effort Is Not Something to Hide", "Ch 2"),
    "topic": "Effort as visible strength rather than something to hide, from Chapter 2's discussion of what mindsets do to the meaning of effort",
    "summary": ("Film 4. Chapter 2, 'Mindsets Change the Meaning of Effort.' A fixed mindset treats effort as proof "
                "that ability was missing to begin with, so it gets hidden. A growth mindset treats effort as the "
                "thing that makes ability. Grounded in the book's own TOC-confirmed section title, told through the "
                "hidden root system beneath a small visible plant."),
    "existing": [{"title": "Hard-work-pays-off children's sayings", "url": SRC, "source": "web", "angle": "Work hard!",
                  "what_it_covers": "States the conclusion without explaining why effort gets hidden in the first place"},
                 {"title": "Motivational sports-training montages", "url": SRC, "source": "media", "angle": "Push through the pain",
                  "what_it_covers": "Glamorises the training montage without addressing the embarrassment of being seen struggling"},
                 {"title": "Classroom effort-chart posters", "url": SRC, "source": "classroom material", "angle": "Effort counts",
                  "what_it_covers": "Rewards effort with a sticker but never explains why hiding it happens in the first place"}],
    "saturated": ["Generic hard-work-pays-off sayings with no mechanism"],
    "gaps": ["Explaining why effort feels embarrassing to show in the first place", "Making the case that hiding effort is the actual problem, not laziness"],
    "data_points": [("In a fixed mindset, needing effort is read as proof that ability was missing, so effort gets hidden rather than shown.", SRC, "Mindset, Ch 2", "secondary_source", "expected", "the hidden-root device"),
                     ("The chapter's own section title names this directly: mindsets change the meaning of effort.", SRC, "Mindset, Ch 2 (TOC)", "primary_source", "expected", "grounds the claim in the book's own structure"),
                     ("In a growth mindset, effort is what activates ability rather than what exposes its absence.", SRC, "Mindset, Ch 2", "secondary_source", "expected", "reframes effort as the mechanism, not the confession")],
    "questions": ["Why is it embarrassing to be seen trying hard?", "Does needing to practise mean you're not good?", "What's actually happening under the ground when a plant looks small?"],
    "misconceptions": [("Needing to try hard means you're not naturally good", "Effort is what makes ability, not proof it's missing.", "Ch 2"),
                        ("Hiding how hard you tried protects you", "It just hides the exact thing that's working.", "Ch 2")],
    "pain_points": ["Pretending something was easy when it wasn't", "Feeling embarrassed to be seen practising"],
    "angles": [("The Hidden Roots", "narrative", "A small visible plant sits above a huge invisible root system doing all the real work.", "A plant she's actually seen is a physical, felt image for invisible effort.", ["Ch 2"]),
               ("Effort Is Not a Confession", "contrarian", "Trying hard doesn't admit you're bad at something. It's what makes you good at it.", "Directly reverses the shame she may already feel about visible effort.", ["Ch 2"]),
               ("What Nobody Claps For", "evergreen", "The roots never get an audience, but they're the reason the flower can stand at all.", "Names the specific unfairness of invisible work going unrecognised.", ["Ch 2"])],
    "kahneman": "Effort is what activates ability, not a confession that ability was missing.",
    "excluded": ["The sports-specific 'natural' examples from Chapter 4, saved for the next film."],
    "concepts": [
        {"id": "c1", "title": "Why Effort Is Not Something to Hide", "hook": "Diana, that little plant on the windowsill has roots you've never seen, twice as big as the plant itself.", "narrative_structure": "story",
         "visual_approach": "A small visible plant above ground beside a full cutaway view of its large tangled root system underground.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 140,
         "key_points": ["What shows above ground is small compared to what's happening below", "Effort is the roots, not the flower", "Hiding effort is like cutting your own roots off", "The visible bit only exists because of the invisible work", "Let your roots be seen sometimes"],
         "core_message": "The flower isn't the strong part. The roots are. And they're allowed to show.", "cta": "Let someone see you practising, not just the finished thing.", "tone": "Warm and grounding.",
         "why_this_works": "It gives invisible effort a physical shape she can picture the next time she's tempted to hide trying.", "grounded_in": ["Ch 2"]},
        {"id": "c2", "title": "Not a Confession", "hook": "Trying hard isn't admitting anything.", "narrative_structure": "comparison",
         "visual_approach": "A plant with its roots cut away, wilting, beside the same plant with roots intact and thriving.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 90, "key_points": ["Cutting off visible effort weakens the whole plant", "The roots are the strength, not the shame"],
         "core_message": "Cut the roots and the flower can't stand.", "cta": "Stop hiding the roots.", "tone": "Firm and warm", "why_this_works": "The direct consequence of hiding effort, folded into c1 as its warning beat.", "grounded_in": ["Ch 2"]},
        {"id": "c3", "title": "What Nobody Claps For", "hook": "Nobody ever claps for the roots.", "narrative_structure": "analogy",
         "visual_approach": "A close view of the root system alone, working quietly underground with no audience.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 75, "key_points": ["The unseen work is still the work that matters most", "An audience was never what made the roots strong"],
         "core_message": "The roots don't need an audience to be doing the real job.", "cta": "Do the roots-work even when nobody's watching.", "tone": "Quiet and grounding.",
         "why_this_works": "The closing reassurance, folded into c1 as its final image.", "grounded_in": ["Ch 2"]}],
    "rationale": "c1 carries the whole root-and-flower image from ground to bloom; c2 is folded in as its cautionary middle, since both share one continuous plant.",
    "device_short": "a small visible plant above a large tangled root system doing the real work underground",
    "art_direction": "New device: a small simple plant shown above ground with a full cutaway revealing an unexpectedly large, tangled root system beneath it.",
    "device_lock": "One small plain plant with a few leaves above a clean soil line; below the line, a large tangled network of roots in warm brown tones, clearly more extensive than the visible plant. No numerals.",
    "tradeoffs": [{"tradeoff": "Showing a famous person's hidden practice versus a generic plant metaphor", "recommendation": "The plant metaphor",
                   "quality_impact": "A named example would need a specific verified biography; the plant carries the idea for any effort she's hiding, not one story she may not relate to."}],
    "energy_curve": "Warm and grounding through the root reveal. Firm at not-a-confession. Gentle at her own hiding. Encouraging at the close.",
    "sample_section": "s5", "human_note": "Section s5 is the core reversal. Say it like a genuine correction, warmly.",
    "pause_beats": [{"section": "s4", "purpose": "She takes in how much bigger the roots are than the plant"}, {"section": "s9", "purpose": "She thinks about effort she's hidden"}, {"section": "s13", "purpose": "She decides to let something show"}],
    "grounded_in": {"s1_to_s4": "Ch 2, the roots introduced", "s5_to_s8": "Ch 2, effort as confession versus effort as mechanism", "s9_to_s11": "Ch 2 applied to her own hiding", "s12_to_s15": "Ch 2 corrective"},
    "sections": [
        ("s1", "Setup", "Diana, that little plant on the windowsill has roots you've never seen, twice as big as the plant itself.", "Diana, that little plant on the windowsill has roots you've never seen, <break time=\"0.4s\"/> twice as big as the plant itself.", 1.4, "measured", "warm", ["twice as big"], "Inviting curiosity."),
        ("s2", "Above ground", "All you ever see is a few leaves. That's it. That's the whole show, above ground.", "All you ever see is a few leaves. <break time=\"0.4s\"/> That's it. <break time=\"0.4s\"/> That's the whole show, above ground.", 1.4, "measured", "curious", ["whole show"], "Set up the reveal."),
        ("s3", "Below ground", "But underneath, there's this whole tangled mess of roots, working away, that nobody ever claps for.", "But underneath, there's this whole tangled mess of roots, <break time=\"0.4s\"/> working away, <break time=\"0.4s\"/> that nobody ever claps for.", 1.4, "measured", "steady", ["nobody claps"], "A little wistful."),
        ("s4", "The size of it", "Look how much bigger that is than the plant.", "Look how much bigger that is than the plant. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["bigger"], "Pause beat one. Let the scale actually register."),
        ("s5", "The reversal", "And here's the thing, Diana. Effort isn't proof you're not naturally good. Effort is what makes you good. It's the roots.", "And here's the thing, Diana. <break time=\"0.5s\"/> Effort isn't proof you're not naturally good. <break time=\"0.4s\"/> Effort is what makes you good. <break time=\"0.4s\"/> It's the roots.", 1.4, "slow", "warm", ["it's the roots"], "The whole point of the film. Say it clearly and slowly."),
        ("s6", "Why we hide it", "But it's easy to think trying hard means everyone can see you don't already know how. So you hide the roots.", "But it's easy to think trying hard means everyone can see you don't already know how. <break time=\"0.5s\"/> So you hide the roots.", 1.4, "measured", "gentle", ["hide the roots"], "Name the fear without judging it."),
        ("s7", "What happens then", "Cut the roots off to hide them, and the flower can't even stand up any more.", "Cut the roots off to hide them, <break time=\"0.4s\"/> and the flower can't even stand up any more.", 1.4, "measured", "steady", ["can't stand"], "The consequence, plainly stated."),
        ("s8", "It's the opposite", "So it's the exact opposite of what it feels like. The roots aren't the embarrassing part. They're the strong part.", "So it's the exact opposite of what it feels like. <break time=\"0.5s\"/> The roots aren't the embarrassing part. <break time=\"0.4s\"/> They're the strong part.", 1.4, "measured", "warm", ["strong part"], "Reinforce the reversal."),
        ("s9", "Her own hiding", "Think of something you've pretended was easy, when it really wasn't.", "Think of something you've pretended was easy, when it really wasn't. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["pretended"], "Pause beat two. Gentle, no pressure."),
        ("s10", "It's alright", "Everybody does that sometimes. It's alright. I do it too.", "Everybody does that sometimes. <break time=\"0.4s\"/> It's alright. <break time=\"0.4s\"/> I do it too.", 1.4, "measured", "warm", ["I do it too"], "Genuine solidarity."),
        ("s11", "Letting it show", "But you don't have to hide the trying part any more. It's not the part to be embarrassed of.", "But you don't have to hide the trying part any more. <break time=\"0.5s\"/> It's not the part to be embarrassed of.", 1.4, "measured", "encouraging", ["not embarrassed"], "Give explicit permission."),
        ("s12", "Roots showing", "Roots are allowed to show, Diana. That's not weakness. That's where the whole plant is fed from.", "Roots are allowed to show, Diana. <break time=\"0.5s\"/> That's not weakness. <break time=\"0.4s\"/> That's where the whole plant is fed from.", 1.4, "slow", "tender", ["fed from"], "Land the image softly."),
        ("s13", "Try it", "Next time you're practising something hard, let someone actually see you doing it. Not just the finished bit.", "Next time you're practising something hard, let someone actually see you doing it. <break time=\"0.5s\"/> Not just the finished bit. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["actually see"], "Pause beat three. A real instruction to try."),
        ("s14", "It gets easier", "It feels strange the first time. It gets easier to let the roots show, every time after that.", "It feels strange the first time. <break time=\"0.4s\"/> It gets easier to let the roots show, <break time=\"0.4s\"/> every time after that.", 1.4, "measured", "steady", ["easier"], "Honest, forward-looking."),
        ("s15", "Landing", "I've seen your roots, Diana. They're the best part of you. Don't hide them from me.", "I've seen your roots, Diana. <break time=\"0.5s\"/> They're the best part of you. <break time=\"0.4s\"/> Don't hide them from me.", 0.0, "slow", "tender", ["best part"], "Personal, warm, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "NONE", "A small potted plant on a windowsill-like shelf with a few simple leaves, drawn plainly on the page."),
        ("sc2", "s2", "NONE", "The same small plant above a clean horizontal soil line, only the visible leaves shown, nothing below the line."),
        ("sc3", "s3", "NONE", "A cutaway view below the soil line revealing a large tangled network of roots beneath the small plant."),
        ("sc4", "s4", "NONE", "The full plant with both the small visible top and the much larger root system beneath it shown together in one cutaway view."),
        ("sc5", "s5", "DIANA", "The girl looks thoughtful and struck by something, taking in an idea, calm attentive expression."),
        ("sc6", "s6", "DIANA", "The girl looks slightly self-conscious, one hand near her face, gently caught out but not upset."),
        ("sc7", "s7", "NONE", "A plant with its root system shown cut away and severed, the small plant above visibly wilting."),
        ("sc8", "s8", "NONE", "The same plant restored, roots reattached and thriving, standing upright and healthy."),
        ("sc9", "s9", "DIANA", "The girl sits quietly, thinking, hands in her lap, genuinely reflective."),
        ("sc10", "s10", "DIANA", "The girl looks reassured, a small warm smile, at ease."),
        ("sc11", "s11", "DIANA", "The girl stands a little taller, encouraged, open expression."),
        ("sc12", "s12", "NONE", "A close view of the large healthy root system alone, richly detailed and clearly strong."),
        ("sc13", "s13", "DIANA", "The girl practises something with visible focus and effort, unselfconscious, absorbed in trying."),
        ("sc14", "s14", "DIANA", "The girl looks calm and settled, a small confident smile, comfortable being seen trying."),
        ("sc15", "s15", "DIANA", "The girl stands warm and content in soft evening light."),
        ("sc16", "s3", "NONE", "The full cutaway plant and root system, warmly lit, the roots glowing gently as if alive with activity."),
        ("sc17", "s12", "NONE", "The large root system shown alone, spreading wide and strong beneath where the plant would be."),
        ("sc18", "s15", "NONE", "The small plant standing healthy above ground with its full root system visible beneath it, both parts equally warmly lit."),
    ],
    "heroes": {"sc4", "sc16", "sc18"}, "wides": {"sc4", "sc17", "sc18"},
}
FILM4["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc5", "sc6", "sc9", "sc10", "sc11", "sc13", "sc14", "sc15"}),
    "NOICON": (G.NOICON, {"sc5", "sc6", "sc9", "sc10", "sc11", "sc13", "sc14", "sc15"}),
    "PLANT": (("The plant is one small simple plant with a few plain leaves. Roots are a warm brown tangled network "
               "drawn clearly beneath a horizontal soil line. No pot decoration, no background scenery, no writing."),
              {"sc1", "sc2", "sc3", "sc4", "sc7", "sc8", "sc12", "sc16", "sc17", "sc18"}),
}

# ---------------------------------------------------------------- FILM 5
FILM5 = {**base(5, "diana-mindset-no-natural", "DianaNoSuchThingNatural", "There's No Such Thing as a Natural", "Ch 3-4"),
    "topic": "The myth of the 'natural,' from the book's chapters on ability and sport, told as Dad explaining that what looks effortless was practised until it looked that way",
    "summary": ("Film 5. Chapters 3 and 4. The book repeatedly challenges the idea of the 'natural': skill that looks "
                "effortless is usually the visible tip of enormous unseen practice. Grounded in the book's own "
                "contents page ('The Idea of the Natural') and its discussion of ability and accomplishment."),
    "existing": [{"title": "Sports-hero highlight reels for children", "url": SRC, "source": "media", "angle": "Look how amazing they are",
                  "what_it_covers": "Shows the finished skill, never the thousands of hours behind it"},
                 {"title": "Prodigy documentaries and biopics", "url": SRC, "source": "media", "angle": "Born to do this",
                  "what_it_covers": "Frames the story around innate gift rather than the unglamorous repetition behind it"},
                 {"title": "'Talent will out' inspirational quotes", "url": SRC, "source": "web", "angle": "Cream rises to the top",
                  "what_it_covers": "Treats talent as a fixed thing that simply reveals itself, with no mention of practice"}],
    "saturated": ["Highlight-reel sports content that shows only the finished result"],
    "gaps": ["Showing the practice behind the highlight, not just the highlight itself"],
    "data_points": [("The book directly challenges 'the idea of the natural': skill that looks effortless is usually built from enormous unseen practice.", SRC, "Mindset, Ch 4 (TOC: 'The Idea of the Natural')", "primary_source", "expected", "the two-court device"),
                     ("What looks like natural talent is very often the visible result of practice nobody happened to film.", SRC, "Mindset, Ch 3-4", "secondary_source", "surprising", "reframes effortless-looking skill"),
                     ("Believing someone is simply 'a natural' can make a child stop trying, since trying seems to prove the opposite.", SRC, "Mindset, Ch 4", "secondary_source", "expected", "connects to the effort-hiding film")],
    "questions": ["Why do some people make hard things look easy?", "Does being called a natural mean you don't have to try?", "What happened before the part everyone sees?"],
    "misconceptions": [("Some people are just naturals and don't need to practise", "What looks natural is almost always practice nobody saw.", "Ch 3-4"),
                        ("If it looks effortless, it was effortless", "Effortless-looking is the goal of enormous effort, not the absence of it.", "Ch 3-4")],
    "pain_points": ["Assuming someone else's skill is unearned talent she'll never have", "Giving up because a skill doesn't come immediately"],
    "angles": [("The Empty Court and the Full Court", "narrative", "Everyone sees the full court, the crowd, the win. Nobody sees the empty court at six in the morning.", "Directly visualises the hidden-practice claim.", ["Ch 4"]),
               ("Natural Is a Trick of Timing", "contrarian", "You only ever see the moment after years of practice, never the years.", "Reframes 'natural' as a timing illusion rather than a fact about the person.", ["Ch 3-4"]),
               ("The Word That Stops Trying", "evergreen", "Calling someone a natural can quietly tell them trying isn't the point.", "Connects the myth directly to a behaviour it causes, not just a belief it creates.", ["Ch 4"])],
    "kahneman": "What looks like natural talent is very often years of practice nobody happened to see.",
    "excluded": ["The specific named-athlete case studies from Chapter 4, kept general so it applies to her own life."],
    "concepts": [
        {"id": "c1", "title": "There's No Such Thing as a Natural", "hook": "Diana, everyone claps at the winning goal. Nobody claps at six in the morning, when the court is empty.", "narrative_structure": "story",
         "visual_approach": "An empty court at dawn with a single figure practising alone, beside the same court that night, full of light and a crowd.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 145,
         "key_points": ["What you see is the full court, the win", "What you don't see is the empty court, alone, for years", "Natural is just a word for practice you never watched", "Calling someone a natural can make trying feel pointless", "Ask what the empty court looked like"],
         "core_message": "You never see the empty court. That's not because it wasn't there. It's because nobody was watching yet.", "cta": "When something looks effortless, ask what the empty court looked like.", "tone": "Warm and demystifying.",
         "why_this_works": "It gives her a concrete image for the invisible years behind any skill that looks easy.", "grounded_in": ["Ch 3-4"]},
        {"id": "c2", "title": "A Trick of Timing", "hook": "You only ever arrive after the years, never during them.", "narrative_structure": "analogy",
         "visual_approach": "A long dim corridor leading to one bright lit doorway at the very end.", "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old",
         "target_platform": "generic", "target_duration_seconds": 85, "key_points": ["The bright moment is the end of a long corridor, not a separate thing", "You only ever arrive after the corridor, never during it"], "core_message": "You're seeing the end, not the whole hallway.",
         "cta": "Remember the hallway is always there.", "tone": "Curious", "why_this_works": "A second concrete image for the same idea, folded into c1 as its closing scene.", "grounded_in": ["Ch 3-4"]},
        {"id": "c3", "title": "The Word That Stops Trying", "hook": "Calling someone a natural can quietly tell them trying isn't the point.", "narrative_structure": "problem_solution",
         "visual_approach": "The empty dawn court, now with the lone figure pausing mid-motion, uncertain whether to continue.", "suggested_playbook": "custom-atelier-storybook", "target_audience": "The same 8-year-old",
         "target_platform": "generic", "target_duration_seconds": 70, "key_points": ["The word natural can make trying feel pointless", "Ask what the empty court looked like instead"],
         "core_message": "The word 'natural' can quietly take the trying away from someone.", "cta": "Ask about the empty court, not just the win.", "tone": "Thoughtful.",
         "why_this_works": "Names the practical harm of the myth, folded into c1 as its final caution.", "grounded_in": ["Ch 4"]}],
    "rationale": "c1 carries the full empty-court-to-full-court arc; c2 is folded in as its final reframing image, since both illustrate the same timing illusion.",
    "device_short": "the same court shown empty at dawn and full at night",
    "art_direction": "New device: one plain court or open space shown twice, empty and dim at dawn with a single figure practising, and lit and full at night with a crowd.",
    "device_lock": "One simple flat open court or floor space drawn identically both times. Dawn version: dim, empty, one small distant figure. Night version: bright, warm, full of small simple crowd shapes. No numerals.",
    "tradeoffs": [{"tradeoff": "Naming a specific real athlete versus keeping the figure anonymous", "recommendation": "Keep the figure anonymous",
                   "quality_impact": "A named athlete would need a verified biography and risks the lesson feeling like it's about someone else's life rather than a pattern she can apply to her own."}],
    "energy_curve": "Warm and scene-setting at the two courts. Curious at the timing reveal. Gentle at her own comparisons. Encouraging at the close.",
    "sample_section": "s6", "human_note": "Section s6 is the core reframe. Slow down and mean it.",
    "pause_beats": [{"section": "s4", "purpose": "She holds both images, empty and full, side by side"}, {"section": "s10", "purpose": "She thinks of someone she's called a natural"}, {"section": "s13", "purpose": "She reframes that person for herself"}],
    "grounded_in": {"s1_to_s4": "Ch 4, the empty and full court", "s5_to_s8": "Ch 3-4, natural as a timing illusion", "s9_to_s11": "Ch 4 applied to her own comparisons", "s12_to_s15": "Ch 3-4 corrective"},
    "sections": [
        ("s1", "Setup", "Diana, everyone claps at the winning goal. Nobody claps at six in the morning, when the court is empty.", "Diana, everyone claps at the winning goal. <break time=\"0.4s\"/> Nobody claps at six in the morning, <break time=\"0.4s\"/> when the court is empty.", 1.4, "measured", "warm", ["empty"], "Set the two images clearly."),
        ("s2", "The empty court", "Picture that empty court. One person, alone, practising the same shot over and over. No crowd. No noise.", "Picture that empty court. <break time=\"0.4s\"/> One person, alone, practising the same shot over and over. <break time=\"0.4s\"/> No crowd. <break time=\"0.3s\"/> No noise.", 1.4, "measured", "steady", ["alone"], "Slow, atmospheric."),
        ("s3", "The full court", "Now picture that same court that night. Lights on. Crowd cheering. Same person, same shot, and everyone calls it natural.", "Now picture that same court that night. <break time=\"0.4s\"/> Lights on. <break time=\"0.3s\"/> Crowd cheering. <break time=\"0.4s\"/> Same person, same shot, <break time=\"0.4s\"/> and everyone calls it natural.", 1.4, "measured", "curious", ["natural"], "Let the word land with a little irony."),
        ("s4", "Same person", "Same person. Same shot. The only thing that changed is whether anybody was watching yet.", "Same person. <break time=\"0.3s\"/> Same shot. <break time=\"0.5s\"/> The only thing that changed is whether anybody was watching yet. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["watching"], "Pause beat one. Let this sink in."),
        ("s5", "What natural means", "So natural doesn't mean it came easily. It just means you weren't there for the empty court part.", "So natural doesn't mean it came easily. <break time=\"0.5s\"/> It just means you weren't there for the empty court part.", 1.4, "measured", "steady", ["weren't there"], "The reframe, stated clearly."),
        ("s6", "The reversal", "Nobody is simply a natural, Diana. There's always an empty court somewhere behind them that you never saw.", "Nobody is simply a natural, Diana. <break time=\"0.5s\"/> There's always an empty court somewhere behind them that you never saw.", 1.4, "slow", "warm", ["always an empty court"], "The heart of the film. Slow and certain."),
        ("s7", "The hallway", "It's like walking down a long dim hallway and only arriving at the bright doorway right at the very end.", "It's like walking down a long dim hallway <break time=\"0.4s\"/> and only arriving at the bright doorway right at the very end.", 1.4, "measured", "curious", ["bright doorway"], "A softer second image."),
        ("s8", "You see the end", "You only ever see the doorway. You never see the whole hallway that got them there.", "You only ever see the doorway. <break time=\"0.4s\"/> You never see the whole hallway that got them there.", 1.4, "measured", "steady", ["whole hallway"], "Reinforce."),
        ("s9", "Why it matters", "Because if you think someone's just a natural, trying hard yourself can start to feel pointless.", "Because if you think someone's just a natural, <break time=\"0.4s\"/> trying hard yourself can start to feel pointless.", 1.4, "measured", "gentle", ["pointless"], "Explain why the belief matters."),
        ("s10", "Her own naturals", "Think of someone you've called a natural at something.", "Think of someone you've called a natural at something. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["natural at"], "Pause beat two. Let a real name surface."),
        ("s11", "Their hallway", "Somewhere behind them is an empty court you've never seen. That's the part that actually did it.", "Somewhere behind them is an empty court you've never seen. <break time=\"0.5s\"/> That's the part that actually did it.", 1.4, "measured", "warm", ["actually did it"], "Redirect her admiration to the real cause."),
        ("s12", "So for you too", "And that means your own empty court counts too. Even when nobody's clapping yet.", "And that means your own empty court counts too. <break time=\"0.5s\"/> Even when nobody's clapping yet.", 1.4, "measured", "encouraging", ["counts too"], "Turn it back to her."),
        ("s13", "Try it", "Next time something looks effortless, ask yourself one question. What did the empty court look like for them?", "Next time something looks effortless, ask yourself one question. <break time=\"0.5s\"/> What did the empty court look like for them? <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["empty court"], "Pause beat three. Give her the exact question."),
        ("s14", "Keep going", "And keep going on your own empty court, even on the mornings nobody's there to see it.", "And keep going on your own empty court, <break time=\"0.4s\"/> even on the mornings nobody's there to see it.", 1.4, "measured", "warm", ["keep going"], "Bright, forward-looking."),
        ("s15", "Landing", "I see your empty court, Diana. Even when nobody else does, I do.", "I see your empty court, Diana. <break time=\"0.5s\"/> Even when nobody else does, <break time=\"0.4s\"/> I do.", 0.0, "slow", "tender", ["I do"], "Personal, warm, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "NONE", "A wide open plain court or floor space, empty, in dim pre-dawn light."),
        ("sc2", "s2", "DIANA", "The girl alone on the empty court, practising a simple repeated motion, focused and unobserved."),
        ("sc3", "s3", "NONE", "The same court at night, warmly lit, filled with many small simple crowd silhouettes."),
        ("sc4", "s4", "NONE", "The empty dawn court and the full night court shown together, split across the page, same shape and layout."),
        ("sc5", "s5", "NONE", "The lone figure practising on the empty court, small and distant within the wide space."),
        ("sc6", "s6", "NONE", "A single warm spotlight on the empty court illuminating just the one practising figure, everything else dim."),
        ("sc7", "s7", "NONE", "A long dim corridor stretching into the distance with one small bright doorway glowing at the very far end."),
        ("sc8", "s8", "NONE", "A close view of just the bright doorway alone, warm and inviting, with no hallway visible."),
        ("sc9", "s9", "DIANA", "The girl looks thoughtful, taking in something important, calm and attentive."),
        ("sc10", "s10", "DIANA", "The girl sits quietly, thinking, hand resting near her chin, genuinely reflective."),
        ("sc11", "s11", "NONE", "The empty dawn court again, quiet and still, but now warmly and gently lit rather than dim."),
        ("sc12", "s12", "DIANA", "The girl practises something on her own with quiet determination, unselfconscious."),
        ("sc13", "s13", "DIANA", "The girl stands with one hand raised slightly, alert, catching a thought."),
        ("sc14", "s14", "DIANA", "The girl continues practising with warm morning light beginning to fill the space around her."),
        ("sc15", "s15", "DIANA", "The girl stands calm and content in soft evening light."),
        ("sc16", "s6", "NONE", "The empty court glowing warm as dawn breaks, the lone figure now surrounded by soft golden light."),
        ("sc17", "s3", "NONE", "The full lit court at night, wide view, warm and celebratory with the crowd shapes."),
        ("sc18", "s15", "NONE", "The empty court at dawn, now peaceful and glowing gently, a single set of footprints crossing it."),
    ],
    "heroes": {"sc6", "sc16", "sc18"}, "wides": {"sc1", "sc3", "sc4", "sc7", "sc17"},
}
FILM5["clauses"] = {
    "OPEN": (G.OPEN, {"sc9", "sc10", "sc13", "sc14", "sc15"}),
    "NOICON": (G.NOICON, {"sc9", "sc10", "sc13", "sc14", "sc15"}),
    "COURT": (("The court is one plain flat open floor space drawn simply on cream paper, no walls, no stands, no "
               "detailed architecture. Crowd shapes are simple small silhouettes, not individually detailed. No "
               "numerals, no writing, no scoreboards."),
              {"sc1", "sc2", "sc3", "sc4", "sc5", "sc6", "sc11", "sc12", "sc16", "sc17", "sc18"}),
    "HALL": (("The hallway is a simple flat perspective corridor drawn plainly with no decoration, ending in one "
              "glowing doorway. No numerals, no writing, no signage."), {"sc7", "sc8"}),
}

if __name__ == "__main__":
    G_FILMS = {"m02": FILM2, "m03": FILM3, "m04": FILM4, "m05": FILM5}
    args = sys.argv[1:]
    slugs = [a for a in args if a in G_FILMS] or list(G_FILMS)
    for key in slugs:
        f = G_FILMS[key]
        if "init" in args:
            G.init(f)
        if "build" in args:
            G.build(f)
        if "sheet" in args:
            G.sheet(f)
