"""Mindset series, films 6-9 of 25: Praise That Backfires / Praise the Practice / Champions After Losing / Compare to Yesterday."""
import sys
import filmgen as G
from mindset_a import base, SRC

# ---------------------------------------------------------------- FILM 6
FILM6 = {**base(6, "diana-mindset-praise-backfire", "DianaPraiseBackfire", "Why 'You're So Clever' Can Backfire", "Ch 3"),
    "topic": "The danger of praising fixed traits, from Chapter 3's discussion of praise and labels, told as Dad explaining why a compliment can quietly become a cage",
    "summary": ("Film 6. Chapter 3, 'The Danger of Praise and Positive Labels.' Praising a fixed trait like "
                "cleverness, rather than the process, can make a child more cautious: if being clever is the whole "
                "identity, a hard problem risks proving the label wrong, so easy, safe choices start to feel safer "
                "than growth. Grounded in the book's own chapter title."),
    "existing": [{"title": "Generic praise-your-child advice", "url": SRC, "source": "parenting web content", "angle": "Always praise your child",
                  "what_it_covers": "Encourages praise without distinguishing the kind that helps from the kind that traps"},
                 {"title": "Self-esteem-movement classroom posters", "url": SRC, "source": "classroom material", "angle": "You're special",
                  "what_it_covers": "Praises identity broadly without ever naming the specific cost of trait-based praise"},
                 {"title": "Celebrity-parenting compliment tips", "url": SRC, "source": "web", "angle": "Say something nice every day",
                  "what_it_covers": "Focuses on frequency of praise, not on which part of the moment the praise points at"}],
    "saturated": ["Blanket praise-more parenting advice with no distinction between praise types"],
    "gaps": ["Explaining specifically why 'you're so clever' can make a child avoid hard things", "A father catching himself using this kind of praise"],
    "data_points": [("Praising a fixed trait can make a child more cautious about attempting hard tasks, since failure would seem to disprove the trait.", SRC, "Mindset, Ch 3 (TOC: 'The Danger of Praise and Positive Labels')", "primary_source", "surprising", "the label-as-cage device"),
                     ("The chapter title itself names the risk directly: praise and positive labels can be a danger, not simply a kindness.", SRC, "Mindset, Ch 3 (TOC)", "primary_source", "expected", "grounds the claim in the book's own structure"),
                     ("The effect applies specifically to trait praise like 'clever' or 'talented', not to praise of effort or strategy.", SRC, "Mindset, Ch 3", "secondary_source", "expected", "sets up the corrective in the next film")],
    "questions": ["Why would being called clever ever be a bad thing?", "Does a compliment ever make you want to try less?", "What's the difference between a label and a description?"],
    "misconceptions": [("More praise is always better", "The kind of praise matters more than the amount.", "Ch 3"), ("Being called clever should make you braver", "It can make hard things feel riskier, because failing would seem to disprove the label.", "Ch 3")],
    "pain_points": ["Avoiding a hard challenge because failing might look bad", "Choosing the easy option to protect a reputation for being clever"],
    "angles": [("The Label That Becomes a Cage", "narrative", "A gift label tied on with string can quietly become a cage around what you're willing to try.", "Makes an abstract danger physically visible.", ["Ch 3"]),
               ("Dad Catches Himself", "evergreen", "I've called you clever plenty of times. I want to be more careful with that word.", "Models self-correction rather than only correcting her.", ["Ch 3"]),
               ("Protecting the Label", "contrarian", "Once a label feels true, protecting it can matter more than growing.", "Names the specific behaviour the danger produces, not just the feeling.", ["Ch 3"])],
    "kahneman": "Praising a fixed trait can make hard, risky tasks feel like threats to that trait rather than opportunities.",
    "excluded": ["The negative-labels section, saved for a distinction in the next film's guardrails."],
    "concepts": [
        {"id": "c1", "title": "Why 'You're So Clever' Can Backfire", "hook": "Diana, I want to tell you something about a word I've said to you a lot. Clever.", "narrative_structure": "story",
         "visual_approach": "A small paper gift label tied on with string that slowly grows bars, becoming a small cage around whoever wears it.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 140,
         "key_points": ["A label like clever feels good to hear", "But it can make hard things feel like a threat to the label", "You start protecting the label instead of growing", "The label wasn't the problem, only what it made you afraid of", "Dad is trying to say it differently now"],
         "core_message": "A label tied on with string can start to feel like a cage, even though nobody meant it that way.", "cta": "Notice if a compliment makes you want to try less, not more.", "tone": "Warm, a little rueful, self-correcting.",
         "why_this_works": "It's honest about a parenting habit rather than only a lesson aimed at her.", "grounded_in": ["Ch 3"]},
        {"id": "c2", "title": "Protecting the Label", "hook": "Once a label feels true, keeping it safe can matter more than growing.", "narrative_structure": "problem_solution",
         "visual_approach": "The paper tag with a single bar growing, shown at the exact moment a choice narrows from two doors to one.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 80,
         "key_points": ["A label starts to feel like something to defend", "Defending it can quietly close off harder choices"],
         "core_message": "Protecting a label and growing can start to pull in different directions.", "cta": "Notice when you're protecting a label instead of choosing freely.", "tone": "Steady and clear.",
         "why_this_works": "Names the specific behaviour the danger produces, folded into c1 as its middle beat.", "grounded_in": ["Ch 3"]},
        {"id": "c3", "title": "The Blank Tag", "hook": "What if the tag never needed anything written on it at all?", "narrative_structure": "analogy",
         "visual_approach": "The blank paper tag, free of bars, in warm closing light.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 70,
         "key_points": ["A blank tag never needs defending", "Not everything about you needs a name to be real"], "core_message": "A tag with nothing written on it never needs a cage.", "cta": "Let some things about yourself stay unlabelled.",
         "tone": "Tender.", "why_this_works": "The closing image, folded into c1 as its final beat.", "grounded_in": ["Ch 3"]}],
    "rationale": "One idea carries the whole film: the label itself is warm, but its quiet cost needs the full arc to land honestly, including Dad's own self-correction.",
    "device_short": "a small paper gift label that slowly grows bars into a cage",
    "art_direction": "New device: a small paper gift tag tied on with string, which gradually sprouts thin bars around itself until it resembles a tiny cage.",
    "device_lock": "One small rectangular paper tag on a string, plain and blank, no writing. As the film progresses the same tag grows thin vertical bars around it, becoming a small cage shape. No numerals, no letters.",
    "tradeoffs": [{"tradeoff": "Writing the word 'clever' on the label versus leaving it blank", "recommendation": "Leave it blank",
                   "quality_impact": "No lettering may appear in any illustration; a blank label with a cage growing around it carries the idea without needing text."}],
    "energy_curve": "Warm at the opening confession. Curious as the cage grows. Gentle and honest through the self-correction. Settled at the close.",
    "sample_section": "s9", "human_note": "Section s9 is Dad admitting his own habit. Genuine, not performed guilt.",
    "pause_beats": [{"section": "s5", "purpose": "She notices the cage forming and takes it in"}, {"section": "s10", "purpose": "She thinks of a time a compliment made her cautious"}, {"section": "s13", "purpose": "She considers what she'd rather hear instead"}],
    "grounded_in": {"s1_to_s4": "Ch 3, the label introduced warmly", "s5_to_s8": "Ch 3, the cage forming, the risk explained", "s9_to_s11": "Ch 3, Dad's own self-correction", "s12_to_s15": "Ch 3 corrective, setting up the next film"},
    "sections": [
        ("s1", "Setup", "Diana, I want to tell you something about a word I've said to you a lot. Clever.", "Diana, I want to tell you something about a word I've said to you a lot. <break time=\"0.4s\"/> Clever.", 1.4, "measured", "warm", ["clever"], "Gentle, a little confessional."),
        ("s2", "The good part", "It's a lovely word to hear. I mean it every time. It comes from a good place.", "It's a lovely word to hear. <break time=\"0.4s\"/> I mean it every time. <break time=\"0.4s\"/> It comes from a good place.", 1.4, "measured", "warm", ["good place"], "Genuine, not a setup for a trick."),
        ("s3", "The tag", "Picture it like a little paper tag, tied on with string. A nice one. A gift.", "Picture it like a little paper tag, tied on with string. <break time=\"0.4s\"/> A nice one. <break time=\"0.4s\"/> A gift.", 1.4, "measured", "curious", ["gift"], "Picture-building."),
        ("s4", "The quiet worry", "But here's what I didn't think about. If clever becomes who you are, then getting something wrong starts to feel like losing the tag.", "But here's what I didn't think about. <break time=\"0.5s\"/> If clever becomes who you are, <break time=\"0.4s\"/> then getting something wrong starts to feel like losing the tag.", 1.4, "measured", "steady", ["losing the tag"], "The hinge, stated carefully."),
        ("s5", "The cage grows", "So little bars start growing around it, without anyone meaning them to. To protect the tag.", "So little bars start growing around it, <break time=\"0.4s\"/> without anyone meaning them to. <break time=\"0.4s\"/> To protect the tag. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["bars"], "Pause beat one. Let the image form."),
        ("s6", "What the cage does", "And once there's a cage, you start picking the safe thing instead of the hard thing. Just to keep the tag safe.", "And once there's a cage, <break time=\"0.4s\"/> you start picking the safe thing instead of the hard thing. <break time=\"0.4s\"/> Just to keep the tag safe.", 1.4, "measured", "steady", ["safe thing"], "Explain the consequence plainly."),
        ("s7", "Nobody meant it", "Nobody put those bars there on purpose. Not me, not you. They just grow, quietly, around a label.", "Nobody put those bars there on purpose. <break time=\"0.4s\"/> Not me, not you. <break time=\"0.4s\"/> They just grow, quietly, around a label.", 1.4, "measured", "gentle", ["quietly"], "No blame in the delivery."),
        ("s8", "It's not the word", "It was never really about the word clever. It's about what the word made you afraid of losing.", "It was never really about the word clever. <break time=\"0.5s\"/> It's about what the word made you afraid of losing.", 1.4, "measured", "steady", ["afraid of losing"], "Clarify the real mechanism."),
        ("s9", "Dad's confession", "So I want to be more careful with that word now, Diana. I'm going to try to say it differently.", "So I want to be more careful with that word now, Diana. <break time=\"0.5s\"/> I'm going to try to say it differently.", 1.4, "measured", "tender", ["more careful"], "Genuine, this is the honesty beat."),
        ("s10", "Her turn", "Has a compliment ever made you want to try less instead of more? Have a think.", "Has a compliment ever made you want to try less instead of more? <break time=\"0.5s\"/> Have a think. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["try less"], "Pause beat two. Real reflection."),
        ("s11", "It's alright", "It's a strange thing to notice, isn't it. It doesn't feel like it should work that way.", "It's a strange thing to notice, isn't it. <break time=\"0.4s\"/> It doesn't feel like it should work that way.", 1.4, "measured", "curious", ["strange"], "Validate the counterintuitive feeling."),
        ("s12", "Not banning it", "I'm not going to stop telling you you're clever. I just want the cage to stay small, or better, not grow at all.", "I'm not going to stop telling you you're clever. <break time=\"0.5s\"/> I just want the cage to stay small, <break time=\"0.3s\"/> or better, not grow at all.", 1.4, "measured", "warm", ["stay small"], "Reassure, don't overcorrect."),
        ("s13", "What you'd rather hear", "What would you rather hear instead, when you've worked hard at something? Think about it.", "What would you rather hear instead, when you've worked hard at something? <break time=\"0.4s\"/> Think about it. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["rather hear"], "Pause beat three. Sets up the next film's tool."),
        ("s14", "Coming up", "I've got some ideas about that. We'll get to it next.", "I've got some ideas about that. <break time=\"0.4s\"/> We'll get to it next.", 1.4, "measured", "warm", ["next"], "Bridge to the next film."),
        ("s15", "Landing", "You're not a label to me, Diana. You're a whole person, still becoming. That's so much bigger than one word.", "You're not a label to me, Diana. <break time=\"0.5s\"/> You're a whole person, still becoming. <break time=\"0.4s\"/> That's so much bigger than one word.", 0.0, "slow", "tender", ["whole person"], "Personal, warm, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "NONE", "A single small blank paper gift tag hanging from a plain string, drawn alone on cream paper."),
        ("sc2", "s2", "DIANA", "The girl smiles warmly, pleased and open, receiving something good."),
        ("sc3", "s3", "NONE", "The blank paper tag on its string, a small ribbon bow tied neatly at the top."),
        ("sc4", "s4", "DIANA", "The girl looks slightly hesitant, hovering before a choice, uncertain."),
        ("sc5", "s5", "NONE", "The same paper tag now with a few thin bars beginning to grow around its edges, subtle at first."),
        ("sc6", "s6", "NONE", "The tag now clearly caged, thin bars fully surrounding it on all sides."),
        ("sc7", "s7", "NONE", "The caged tag sitting quietly, the bars plain and unremarkable, nobody visibly responsible."),
        ("sc8", "s8", "NONE", "A close view of the space just inside the bars, empty, the tag itself unchanged at the centre."),
        ("sc9", "s9", "NONE", "One of the thin bars being gently loosened and lifted away by an unseen hand. Only the hand and forearm are visible, no face and no body."),
        ("sc10", "s10", "DIANA", "The girl sits quietly, thinking, hand near her chin, genuinely reflective."),
        ("sc11", "s11", "DIANA", "The girl looks curious and a little surprised, working something out."),
        ("sc12", "s12", "NONE", "The tag with only a few bars left, mostly open now, the tag clearly visible and free."),
        ("sc13", "s13", "DIANA", "The girl looks thoughtful and hopeful, considering something new."),
        ("sc14", "s14", "DIANA", "The girl looks forward with quiet anticipation, open expression."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s7", "NONE", "The caged tag glowing gently warm, softened rather than harsh despite the bars."),
        ("sc17", "s12", "NONE", "The tag with its bars nearly gone, hanging loose and open on its string."),
        ("sc18", "s15", "NONE", "The blank paper tag, entirely free of any bars, hanging simply and openly on its string in warm light."),
    ],
    "heroes": {"sc6", "sc9", "sc17", "sc18"}, "wides": set(),
}
FILM6["clauses"] = {
    "OPEN": (G.OPEN, {"sc2", "sc4", "sc9", "sc10", "sc11", "sc13", "sc14", "sc15"}),
    "NOICON": (G.NOICON, {"sc2", "sc4", "sc9", "sc10", "sc11", "sc13", "sc14", "sc15"}),
    "TAG": (("The tag is one small plain rectangular paper gift label on a string, drawn simply on cream paper, "
             "completely blank with no writing, no letters, no symbols. Cage bars are thin plain vertical lines. "
             "No numerals anywhere."), {"sc1", "sc3", "sc5", "sc6", "sc7", "sc8", "sc9", "sc12", "sc16", "sc17", "sc18"}),
}

# ---------------------------------------------------------------- FILM 7
FILM7 = {**base(7, "diana-mindset-praise-practice", "DianaPraisePractice", "Praise the Practice, Not the Person", "Ch 3"),
    "topic": "Praising process over person, the book's own corrective to trait praise, told as Dad practising a new kind of compliment",
    "summary": ("Film 7. Chapter 3. The book's corrective to the danger explored in the previous film: praise "
                "aimed at effort, strategy and choices grows a child's engagement with challenge, while praise "
                "aimed at fixed traits does not. This film gives Diana the exact shape of the better compliment, "
                "grounded in the same chapter as the previous film's warning."),
    "existing": [{"title": "Generic 'praise effort' parenting tips", "url": SRC, "source": "web", "angle": "Praise the effort",
                  "what_it_covers": "States the rule without giving a child the actual shape of the sentence"},
                 {"title": "Teacher-training compliment scripts", "url": SRC, "source": "professional development material", "angle": "Use specific praise",
                  "what_it_covers": "Aimed at adult practice, never translated into something a child can recognise for herself"},
                 {"title": "Positive-parenting affirmation cards", "url": SRC, "source": "web", "angle": "Say affirming things daily",
                  "what_it_covers": "Offers stock phrases without explaining why one phrase works better than another"}],
    "saturated": ["Praise-effort tips aimed at parents rather than spoken to the child"],
    "gaps": ["Giving the child, not just the parent, the exact shape of a process compliment", "Showing what a spotlight chooses to light and why that choice matters"],
    "data_points": [("Praise directed at process, effort and strategy sustains engagement with challenge better than praise directed at fixed traits.", SRC, "Mindset, Ch 3", "primary_source", "expected", "the spotlight device"),
                     ("The distinction is not about withholding praise, but about what part of the moment the praise points at.", SRC, "Mindset, Ch 3", "secondary_source", "expected", "clarifies this is not anti-praise"),
                     ("A process compliment names something the child actually did, which they can choose to do again.", SRC, "Mindset, Ch 3", "secondary_source", "expected", "gives the child a repeatable action, not just a trait")],
    "questions": ["What's a better thing to say than 'you're so clever'?", "Why does it matter which part of what I did gets praised?", "Can I ask for the kind of compliment that actually helps?"],
    "misconceptions": [("This means no more compliments", "It means aiming the compliment at the doing, not the being.", "Ch 3"), ("Any praise is the same as any other", "What gets praised is what a person learns to protect or to repeat.", "Ch 3")],
    "pain_points": ["Not knowing what to do with vague praise", "Wanting to be told what actually worked"],
    "angles": [("The Spotlight's Choice", "narrative", "A spotlight can light the hand doing the work, or the person standing still. It's a choice.", "Makes the abstract distinction between trait and process praise visible and simple.", ["Ch 3"]),
               ("Dad Practises Out Loud", "evergreen", "Let me try that sentence again, properly this time.", "Models the better compliment live rather than just describing it.", ["Ch 3"]),
               ("Ask For the Light You Need", "contrarian", "You're allowed to ask for the kind of compliment that actually helps.", "Gives her a concrete, repeatable action rather than only a way of noticing.", ["Ch 3"])],
    "kahneman": "Praise aimed at what someone did, not at who they are, is praise they can act on again.",
    "excluded": ["Detailed classroom-study data comparing praise types, which needs adult framing."],
    "concepts": [
        {"id": "c1", "title": "Praise the Practice, Not the Person", "hook": "Diana, I want to try that compliment again. Properly this time.", "narrative_structure": "story",
         "visual_approach": "A single warm spotlight choosing between lighting a hand mid-motion, doing something, or lighting a still figure standing at rest.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 140,
         "key_points": ["A spotlight on the person says who you are", "A spotlight on the doing says what you did", "Only one of those you can choose to repeat", "This isn't fewer compliments, it's aiming them differently", "You can ask for this kind if you want to"],
         "core_message": "Light the hand doing the work, not just the person standing there. The doing is what you can do again.", "cta": "Next time someone praises you, notice whether they lit the doing or the being.", "tone": "Warm and practical.",
         "why_this_works": "It gives her the exact, usable shape of a better compliment rather than only naming a rule for adults.", "grounded_in": ["Ch 3"]},
        {"id": "c2", "title": "Which One Can You Repeat", "hook": "Which one of those can you choose to do again tomorrow?", "narrative_structure": "problem_solution",
         "visual_approach": "The spotlight shown splitting between the still figure and the working hand, forcing a choice.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 75,
         "key_points": ["A trait can't be chosen again on purpose", "A action can be repeated deliberately"],
         "core_message": "Only one kind of praise points at something you can actually choose to do again.", "cta": "Ask which part of the praise you could repeat on purpose.", "tone": "Curious and practical.",
         "why_this_works": "Sharpens the distinction into a single testable question, folded into c1 as its middle beat.", "grounded_in": ["Ch 3"]},
        {"id": "c3", "title": "Ask For the Light You Need", "hook": "You're allowed to ask for the kind of compliment that actually helps.", "narrative_structure": "tutorial",
         "visual_approach": "The spotlight resting on an open hand at rest, warm and settled.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 65,
         "key_points": ["Asking for process-praise is a real, usable option", "You don't have to wait and hope the right kind arrives"], "core_message": "You can ask someone to aim their praise at what you did.", "cta": "Try asking for this kind of praise once this week.",
         "tone": "Encouraging.", "why_this_works": "Gives her a concrete closing action, folded into c1 as its final beat.", "grounded_in": ["Ch 3"]}],
    "rationale": "One idea, cleanly delivered as Dad correcting himself live, carries the whole film without needing extra concepts.",
    "device_short": "a spotlight choosing to light either a working hand or a standing figure",
    "art_direction": "New device: one warm circular spotlight that can fall on either a hand actively doing something, or a person simply standing still, on plain cream paper.",
    "device_lock": "One soft circular pool of warm light. It falls either on a hand shown mid-action, or on a whole still figure. Only one is lit at a time. No numerals, no writing.",
    "tradeoffs": [{"tradeoff": "Listing many example compliments versus showing the underlying choice once, clearly", "recommendation": "Show the choice once, clearly",
                   "quality_impact": "A list would need memorising; a single repeatable spotlight image transfers to any compliment she hears in the future."}],
    "energy_curve": "Practical and warm from the opening. Curious at the spotlight choice. Encouraging at the invitation to ask for this kind. Warm at the close.",
    "sample_section": "s6", "human_note": "Section s6 is the actual corrective compliment, modelled live. Say it like you mean it.",
    "pause_beats": [{"section": "s5", "purpose": "She watches the spotlight choose what to light"}, {"section": "s10", "purpose": "She thinks about which kind of praise she's had"}, {"section": "s13", "purpose": "She considers asking for this kind"}],
    "grounded_in": {"s1_to_s4": "Ch 3, the two kinds of praise introduced", "s5_to_s8": "Ch 3, the spotlight choice explained", "s9_to_s11": "Ch 3 applied to her own experience", "s12_to_s15": "Ch 3 corrective, giving her the tool"},
    "sections": [
        ("s1", "Setup", "Diana, I want to try that compliment again. Properly this time.", "Diana, I want to try that compliment again. <break time=\"0.4s\"/> Properly this time.", 1.4, "measured", "warm", ["properly"], "Callback to the previous film, direct."),
        ("s2", "Two spotlights", "There are two ways to shine a light on something someone did. Watch.", "There are two ways to shine a light on something someone did. <break time=\"0.4s\"/> Watch.", 1.4, "measured", "curious", ["watch"], "Set up the demonstration."),
        ("s3", "Light on the person", "One way lights up the person standing there. You're so clever. The light sits on you, just standing.", "One way lights up the person standing there. <break time=\"0.4s\"/> You're so clever. <break time=\"0.4s\"/> The light sits on you, just standing.", 1.4, "measured", "steady", ["just standing"], "Neutral, not accusing."),
        ("s4", "Light on the doing", "The other way lights up the hand, doing the actual work. You kept trying different ways until that piece fit.", "The other way lights up the hand, doing the actual work. <break time=\"0.4s\"/> You kept trying different ways until that piece fit.", 1.4, "measured", "warm", ["actual work"], "Give a real example."),
        ("s5", "Which can you repeat", "Which one of those can you choose to do again tomorrow?", "Which one of those can you choose to do again tomorrow? <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["do again"], "Pause beat one. Let her actually answer."),
        ("s6", "Dad's redo", "So let me say it again. Diana, I noticed how you kept trying different ways until that piece fit. That's what I actually meant.", "So let me say it again. <break time=\"0.5s\"/> Diana, I noticed how you kept trying different ways until that piece fit. <break time=\"0.4s\"/> That's what I actually meant.", 1.4, "slow", "warm", ["actually meant"], "This is the model compliment. Mean it."),
        ("s7", "Not fewer compliments", "This isn't about giving fewer compliments. It's about aiming them at the doing, not just the being.", "This isn't about giving fewer compliments. <break time=\"0.5s\"/> It's about aiming them at the doing, <break time=\"0.4s\"/> not just the being.", 1.4, "measured", "steady", ["aiming"], "Guard against the misconception."),
        ("s8", "Why it matters", "Because the doing is something you can pick up again tomorrow. The being just sits there, hoping to be true again.", "Because the doing is something you can pick up again tomorrow. <break time=\"0.4s\"/> The being just sits there, hoping to be true again.", 1.4, "measured", "curious", ["hoping"], "Land the distinction."),
        ("s9", "Her turn", "Think about praise you've had. Was the light on what you did, or on who you are?", "Think about praise you've had. <break time=\"0.4s\"/> Was the light on what you did, or on who you are?", 1.4, "measured", "gentle", ["what you did"], "Genuine question, not rhetorical."),
        ("s10", "Reflect", "Have a proper think. Either answer is alright, I'm just curious.", "Have a proper think. <break time=\"0.5s\"/> Either answer is alright, I'm just curious. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["either answer"], "Pause beat two. No pressure on the answer."),
        ("s11", "It's a skill", "Aiming a compliment properly is actually a skill. I'm still learning it, if I'm honest.", "Aiming a compliment properly is actually a skill. <break time=\"0.4s\"/> I'm still learning it, if I'm honest.", 1.4, "measured", "warm", ["still learning"], "Genuine humility, continuing the confession from the last film."),
        ("s12", "You can ask", "And here's something you might not know. You're allowed to ask for this kind, if the other kind arrives instead.", "And here's something you might not know. <break time=\"0.5s\"/> You're allowed to ask for this kind, <break time=\"0.4s\"/> if the other kind arrives instead.", 1.4, "measured", "encouraging", ["allowed to ask"], "Give her real agency."),
        ("s13", "Try it", "Next time somebody praises you, ask yourself where the light landed. On the doing, or on you.", "Next time somebody praises you, ask yourself where the light landed. <break time=\"0.5s\"/> On the doing, <break time=\"0.4s\"/> or on you. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["where the light landed"], "Pause beat three. The actual tool."),
        ("s14", "It gets easier to hear", "Once you notice it, you'll start hearing the difference everywhere. It's a good thing to notice.", "Once you notice it, you'll start hearing the difference everywhere. <break time=\"0.4s\"/> It's a good thing to notice.", 1.4, "measured", "warm", ["everywhere"], "Bright, forward-looking."),
        ("s15", "Landing", "I noticed how hard you worked on that today, Diana. That's the light I want to keep shining on you.", "I noticed how hard you worked on that today, Diana. <break time=\"0.5s\"/> That's the light I want to keep shining on you.", 0.0, "slow", "tender", ["keep shining"], "Personal, warm, unhurried close, closing the loop from the previous film."),
    ],
    "spec": [
        ("sc1", "s1", "NONE", "One warm circular spotlight glowing alone in the middle of the page, nothing else visible yet."),
        ("sc2", "s2", "NONE", "The spotlight beginning to move, drawn mid-shift between two positions on the page."),
        ("sc3", "s3", "NONE", "The spotlight settled on a whole still figure standing simply, the figure itself not detailed, just a plain silhouette shape."),
        ("sc4", "s4", "NONE", "The spotlight settled instead on a single hand shown mid-motion, actively doing something, the rest of the page dim."),
        ("sc5", "s5", "DIANA", "The girl looks thoughtfully at the two options, weighing them, curious expression."),
        ("sc6", "s6", "DIANA", "The girl looks warmly at the viewer, receiving something meant sincerely."),
        ("sc7", "s7", "NONE", "The spotlight shown split, half falling on a hand doing something, half on a still figure, both visible together."),
        ("sc8", "s8", "NONE", "The spotlight on the working hand, warm and active, with a faint trailing motion line showing continued activity."),
        ("sc9", "s9", "DIANA", "The girl looks thoughtful, hand near her chin, genuinely reflecting."),
        ("sc10", "s10", "DIANA", "The girl sits quietly, thinking, calm and unhurried."),
        ("sc11", "s11", "NONE", "The warm spotlight glowing steadily, plain and simple, nothing else in the frame."),
        ("sc12", "s12", "DIANA", "The girl looks curious and a little surprised, taking in something new."),
        ("sc13", "s13", "DIANA", "The girl stands alert, listening carefully, catching a thought."),
        ("sc14", "s14", "DIANA", "The girl looks pleased and settled, small warm smile."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s4", "NONE", "The spotlight on the working hand, glowing warmly, the hand mid-action and clearly the focus."),
        ("sc17", "s8", "NONE", "The spotlight fully on the hand doing work, bright and warm, everything else softly dim around it."),
        ("sc18", "s15", "NONE", "The warm spotlight resting gently on a single open hand at rest, calm and settled in soft evening light."),
    ],
    "heroes": {"sc4", "sc8", "sc17", "sc18"}, "wides": set(),
}
FILM7["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc2", "sc3", "sc4", "sc5", "sc6", "sc7", "sc8", "sc9", "sc10", "sc11", "sc12", "sc13", "sc14", "sc15", "sc16", "sc17", "sc18"}),
    "NOICON": (G.NOICON, {"sc1", "sc2", "sc5", "sc6", "sc9", "sc10", "sc11", "sc12", "sc13", "sc14", "sc15"}),
}

# ---------------------------------------------------------------- FILM 8
FILM8 = {**base(8, "diana-mindset-champions-losing", "DianaChampionsLosing", "Champions Are Made in the Empty Gym", "Ch 4"),
    "topic": "How growth-mindset athletes respond to a loss, from Chapter 4's sports material, a direct sequel to the empty-court film about what happens the morning after losing",
    "summary": ("Film 8. Chapter 4. A sequel to the earlier film about hidden practice: this one is about what "
                "happens the morning after a loss. The book contrasts fixed-mindset responses to defeat, which "
                "protect the ego by explaining the loss away, with growth-mindset responses, which examine exactly "
                "what to work on next. Reuses the same empty-court device from the earlier film as a deliberate "
                "two-part story."),
    "existing": [{"title": "Sports-loss consolation content for children", "url": SRC, "source": "web", "angle": "It's okay to lose",
                  "what_it_covers": "Comforts after a loss without showing what the very next useful action looks like"},
                 {"title": "Post-game interview clips with young athletes", "url": SRC, "source": "media", "angle": "Good game, better luck next time",
                  "what_it_covers": "Moves past a loss quickly for camera time, without showing the private morning-after choice"},
                 {"title": "Sportsmanship classroom lessons", "url": SRC, "source": "classroom material", "angle": "Win or lose gracefully",
                  "what_it_covers": "Focuses on how to behave in the moment of losing, not on what to do the next morning"}],
    "saturated": ["Generic it's-okay-to-lose comfort content"],
    "gaps": ["Showing the specific next-morning choice a growth mindset makes after losing", "Connecting directly back to the earlier empty-court film as one continuing story"],
    "data_points": [("Growth-mindset athletes tend to examine a loss for what to work on next, rather than explaining it away to protect their ego.", SRC, "Mindset, Ch 4", "primary_source", "expected", "the morning-after-losing device"),
                     ("Fixed-mindset responses to defeat often involve excuses that protect the sense of being naturally good, rather than useful next steps.", SRC, "Mindset, Ch 4", "secondary_source", "expected", "the contrast this film turns on"),
                     ("This directly continues the empty-court idea from the earlier film: the practice happens again the very next morning, win or lose.", SRC, "Mindset, Ch 4", "secondary_source", "expected", "justifies the reused device as one story")],
    "questions": ["What should I actually do after I lose at something?", "Is it babyish to think hard about a loss instead of just moving on?", "Why do some people make excuses after losing?"],
    "misconceptions": [("Losing means you should just forget it and move on", "Losing is information worth actually looking at, not just brushing off.", "Ch 4"),
                        ("Making an excuse protects you", "It protects the label for a moment, but it stops you learning anything from the loss.", "Ch 4")],
    "pain_points": ["Making an excuse right after losing instead of looking at what happened", "Feeling that thinking about a loss means dwelling on it"],
    "angles": [("The Morning After", "narrative", "The court is empty again the next morning. Who's on it?", "A direct sequel to the earlier film's device, extending the same story.", ["Ch 4"]),
               ("Excuse or Examine", "contrarian", "Explaining a loss away feels better for five minutes. Looking at it is what actually changes anything.", "Turns the abstract fixed-versus-growth contrast into one concrete choice.", ["Ch 4"]),
               ("One Thing, Not the Whole Game", "evergreen", "After a loss, name just one thing you'd work on if you went back right now.", "Gives her a small, doable action instead of a general attitude.", ["Ch 4"])],
    "kahneman": "The morning after a loss, a growth mindset asks what to work on; a fixed mindset looks for a reason it wasn't really a loss.",
    "excluded": ["Named athlete case studies, kept general so the story stays about her own empty court."],
    "concepts": [
        {"id": "c1", "title": "Champions Are Made in the Empty Gym", "hook": "Diana, remember the empty court from before? Let's go back there, the morning after a loss.", "narrative_structure": "story",
         "visual_approach": "The same empty court and full court from the earlier film, now shown the morning after a loss: one figure walks away, one figure walks back onto the empty court.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 135,
         "key_points": ["The loss happened last night, on the full court", "The next morning, the court is empty again", "One response is to explain the loss away and not come back", "The other is to come back and look at exactly what to work on", "This connects directly to the empty court from before"],
         "core_message": "The empty court doesn't care whether you won or lost last night. It's just asking who shows up this morning.", "cta": "After a loss, ask what one thing you'd work on if you went back right now.", "tone": "Warm and steady.",
         "why_this_works": "It extends an image she already knows into new territory, showing the growth mindset in the exact moment it's hardest to hold onto.", "grounded_in": ["Ch 4"]},
        {"id": "c2", "title": "Excuse or Examine", "hook": "Explaining it away feels better for about five minutes.", "narrative_structure": "problem_solution",
         "visual_approach": "A simple fork in the path on the empty court, one direction leading away, one leading back to the centre.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 70,
         "key_points": ["An excuse protects the feeling for a moment", "Examining the loss is what actually changes anything next time"],
         "core_message": "Explaining a loss away and examining it lead to two very different next mornings.", "cta": "Notice whether you're excusing a loss or actually looking at it.", "tone": "Honest and steady.",
         "why_this_works": "Turns the contrast into the exact choice point of the story, folded into c1 as its hinge.", "grounded_in": ["Ch 4"]},
        {"id": "c3", "title": "One Thing, Not the Whole Game", "hook": "Name one thing, just one, you'd work on if you went back right now.", "narrative_structure": "tutorial",
         "visual_approach": "A single set of footprints on the empty court, paused, facing back toward the centre.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 60,
         "key_points": ["A loss can be answered with one small, doable next step", "Picking one thing is enough to start with, the rest can wait"], "core_message": "You don't have to fix the whole game, just the one next thing.", "cta": "Pick one thing to work on after your next loss.",
         "tone": "Encouraging.", "why_this_works": "Keeps the corrective small and usable, folded into c1 as its closing action.", "grounded_in": ["Ch 4"]}],
    "rationale": "One continuous idea, deliberately reusing the previous film's device as its own morning-after chapter, needs no further concepts.",
    "device_short": "the same empty and full court from the earlier film, now the morning after a loss",
    "art_direction": "Reused device: the identical empty dawn court and full night court from the earlier natural-talent film, now depicting the morning after a defeat.",
    "device_lock": "The same plain open court used before. Night version now shows a losing scoreline mood through posture and lighting rather than any numerals. Morning version is the same empty dawn court, one figure choosing to return to it.",
    "tradeoffs": [{"tradeoff": "Generating entirely new court illustrations versus reusing the earlier film's assets directly", "recommendation": "Reuse the earlier film's assets directly for the establishing shots",
                   "quality_impact": "The court is identical by design; regenerating it would risk visual drift between what is meant to be literally the same place, and costs more for no benefit."}],
    "energy_curve": "Quiet and a little heavy at the loss. Steady through the choice. Warm and resolved as the figure returns to the court. Encouraging at the close.",
    "sample_section": "s6", "human_note": "Section s6 is the actual choice point. Let it feel like a real decision, not an obvious one.",
    "pause_beats": [{"section": "s3", "purpose": "She sits with how a loss actually feels, without rushing past it"}, {"section": "s9", "purpose": "She thinks of her own loss and what she did next"}, {"section": "s12", "purpose": "She names one thing she'd work on"}],
    "grounded_in": {"s1_to_s4": "Ch 4, the loss and the next morning", "s5_to_s8": "Ch 4, excuse versus examination", "s9_to_s11": "Ch 4 applied to her own experience", "s12_to_s15": "Ch 4 corrective, connecting back to the empty court"},
    "sections": [
        ("s1", "Setup", "Diana, remember the empty court from before? Let's go back there, the morning after a loss.", "Diana, remember the empty court from before? <break time=\"0.4s\"/> Let's go back there, the morning after a loss.", 1.4, "measured", "warm", ["morning after"], "Callback, direct continuation."),
        ("s2", "The loss", "Last night, on that same court, there was a loss. It happens. It happens to everyone.", "Last night, on that same court, there was a loss. <break time=\"0.4s\"/> It happens. <break time=\"0.4s\"/> It happens to everyone.", 1.4, "measured", "steady", ["happens to everyone"], "Matter-of-fact, no drama."),
        ("s3", "How it feels", "It doesn't feel good. It's not supposed to. Let's not pretend it does.", "It doesn't feel good. <break time=\"0.4s\"/> It's not supposed to. <break time=\"0.4s\"/> Let's not pretend it does. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["not pretend"], "Pause beat one. Honour the real feeling."),
        ("s4", "The empty court again", "But now it's morning. The lights are off. The crowd's gone home. And the court is empty again.", "But now it's morning. <break time=\"0.3s\"/> The lights are off. <break time=\"0.3s\"/> The crowd's gone home. <break time=\"0.4s\"/> And the court is empty again.", 1.4, "measured", "curious", ["empty again"], "Set the scene."),
        ("s5", "Two choices", "There are two things you could do here. Explain the loss away and go home. Or come back and actually look at it.", "There are two things you could do here. <break time=\"0.4s\"/> Explain the loss away and go home. <break time=\"0.4s\"/> Or come back and actually look at it.", 1.4, "measured", "steady", ["actually look"], "Set the contrast clearly."),
        ("s6", "The choice point", "Explaining it away feels better for about five minutes. Looking at it is what actually changes anything.", "Explaining it away feels better for about five minutes. <break time=\"0.4s\"/> Looking at it is what actually changes anything.", 1.4, "slow", "warm", ["actually changes"], "The heart of the film."),
        ("s7", "Who comes back", "So the person who comes back to the empty court isn't pretending the loss didn't hurt. They just decided to do something with it.", "So the person who comes back to the empty court isn't pretending the loss didn't hurt. <break time=\"0.5s\"/> They just decided to do something with it.", 1.4, "measured", "steady", ["do something with it"], "Reframe returning, not denial."),
        ("s8", "Not about forgetting", "This isn't about forgetting the loss and moving on quickly. It's about staying with it just long enough to learn from it.", "This isn't about forgetting the loss and moving on quickly. <break time=\"0.5s\"/> It's about staying with it just long enough to learn from it.", 1.4, "measured", "gentle", ["long enough"], "Correct the misconception directly."),
        ("s9", "Her own loss", "Think of a time you lost at something. What did you tell yourself the next day?", "Think of a time you lost at something. <break time=\"0.4s\"/> What did you tell yourself the next day?", 1.4, "measured", "gentle", ["next day"], "Genuine question."),
        ("s10", "Reflect", "Was it an excuse, or was it an actual look at what happened? Either is alright to admit.", "Was it an excuse, or was it an actual look at what happened? <break time=\"0.4s\"/> Either is alright to admit. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["alright to admit"], "Pause beat two. Non-judgemental."),
        ("s11", "It's hard both times", "It's hard to lose. And it's hard to go back to the empty court afterwards. Both things can be true.", "It's hard to lose. <break time=\"0.4s\"/> And it's hard to go back to the empty court afterwards. <break time=\"0.4s\"/> Both things can be true.", 1.4, "measured", "steady", ["both true"], "Honour the difficulty of the corrective too."),
        ("s12", "One thing", "So here's your move. After a loss, name one thing, just one, you'd work on if you went back right now.", "So here's your move. <break time=\"0.5s\"/> After a loss, name one thing, just one, <break time=\"0.4s\"/> you'd work on if you went back right now. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["one thing"], "Pause beat three. The actual tool, kept small."),
        ("s13", "Just one thing", "Just one. Not the whole game. One thing is enough to start with.", "Just one. <break time=\"0.4s\"/> Not the whole game. <break time=\"0.4s\"/> One thing is enough to start with.", 1.4, "measured", "warm", ["enough to start"], "Keep the ask manageable."),
        ("s14", "Same court, new day", "It's the same court as before, Diana. Win or lose, it's still there in the morning, waiting.", "It's the same court as before, Diana. <break time=\"0.4s\"/> Win or lose, it's still there in the morning, <break time=\"0.4s\"/> waiting.", 1.4, "measured", "warm", ["still there"], "Callback to the earlier film, tie the two together."),
        ("s15", "Landing", "I'll walk back onto the court with you, Diana, win or lose. That part never changes.", "I'll walk back onto the court with you, Diana, win or lose. <break time=\"0.5s\"/> That part never changes.", 0.0, "slow", "tender", ["never changes"], "Personal, warm, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "NONE", "The same wide open plain court, empty and quiet, now lit in the pale grey light just before dawn."),
        ("sc2", "s2", "NONE", "The full court from the night before, lit but now quiet and still, the crowd shapes gone, a subdued rather than celebratory mood."),
        ("sc3", "s3", "DIANA", "The girl sits with her shoulders low, quiet and downcast but not distraught, honestly feeling a loss."),
        ("sc4", "s4", "NONE", "The wide open plain court, empty, lights off, in dim early morning light."),
        ("sc5", "s5", "NONE", "A simple fork in a path on the empty court: one direction leads away off the page, one leads back toward the centre of the court."),
        ("sc6", "s6", "NONE", "A single set of footprints on the empty court, paused at the fork, facing back toward the centre."),
        ("sc7", "s7", "NONE", "A small figure walking back onto the empty court from its edge, not rushing, quietly choosing to return."),
        ("sc8", "s8", "NONE", "A close view of the empty court's surface, calm and quiet, a soft warm patch of morning light falling across it."),
        ("sc9", "s9", "DIANA", "The girl sits thinking, hand near her chin, genuinely reflective, calm."),
        ("sc10", "s10", "DIANA", "The girl looks down in quiet thought, honest and unhurried."),
        ("sc11", "s11", "DIANA", "The girl looks steady, accepting something difficult without flinching from it."),
        ("sc12", "s12", "DIANA", "The girl stands with one hand raised slightly, naming something, focused and clear."),
        ("sc13", "s13", "DIANA", "The girl looks resolved and calm, having settled on something small and doable."),
        ("sc14", "s14", "NONE", "The empty court glowing warm as dawn breaks, quiet and steady, waiting."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s7", "NONE", "The empty court at dawn, warm and quiet, one small figure walking back onto it from the edge."),
        ("sc17", "s4", "NONE", "A close view of the empty court's surface, dim and still, in the early morning light."),
        ("sc18", "s15", "NONE", "The empty dawn court, peaceful and glowing gently, a single set of footprints crossing it toward the centre."),
    ],
    "heroes": {"sc6", "sc16"}, "wides": {"sc1", "sc2", "sc4", "sc7"},
}
FILM8["clauses"] = {
    "OPEN": (G.OPEN, {"sc3", "sc5", "sc6", "sc8", "sc9", "sc10", "sc11", "sc12", "sc13", "sc15", "sc16"}),
    "NOICON": (G.NOICON, {"sc3", "sc9", "sc10", "sc11", "sc12", "sc13", "sc15"}),
    "COURT": (("The court is the identical plain open floor space style used in the earlier natural-talent film: "
               "no walls, no stands, no numerals, no scoreboards, no detailed architecture."),
              {"sc1", "sc2", "sc4", "sc5", "sc6", "sc7", "sc8", "sc14", "sc16", "sc17", "sc18"}),
}

# ---------------------------------------------------------------- FILM 9
FILM9 = {**base(9, "diana-mindset-compare-yesterday", "DianaCompareYesterday", "Compare Yourself Only to Yesterday", "Ch 4"),
    "topic": "Comparing progress against your own past self rather than against others, drawn from the book's discussion of taking charge of success",
    "summary": ("Film 9. Chapter 4, 'Taking Charge of Success.' A growth mindset measures progress against where "
                "you started, not against someone else's current position, because the second comparison tells you "
                "nothing true about your own growth. Grounded in the book's own section on defining success for "
                "yourself."),
    "existing": [{"title": "Generic 'don't compare yourself to others' sayings", "url": SRC, "source": "web", "angle": "Comparison is the thief of joy",
                  "what_it_covers": "States the rule as a mood without giving a specific, better comparison to make instead"},
                 {"title": "Social-media 'stay in your lane' advice", "url": SRC, "source": "web", "angle": "Focus on yourself",
                  "what_it_covers": "Tells you to stop looking sideways without offering an actual replacement measure"},
                 {"title": "School report-card ranking systems", "url": SRC, "source": "classroom material", "angle": "Where you stand in the class",
                  "what_it_covers": "Structurally reinforces sideways comparison as the default measure of progress"}],
    "saturated": ["Comparison-is-the-thief-of-joy sayings with no replacement measure offered"],
    "gaps": ["Giving a specific, better comparison to make instead of simply banning comparison"],
    "data_points": [("Taking charge of your own success means measuring it against your own starting point rather than someone else's current position.", SRC, "Mindset, Ch 4 (TOC: 'Taking Charge of Success')", "primary_source", "expected", "the two-footprints device"),
                     ("Comparing to another person's current position measures a gap that says nothing true about your own growth.", SRC, "Mindset, Ch 4", "secondary_source", "expected", "explains why the usual comparison misleads"),
                     ("Noticing someone else's position is not itself the problem; using it as the only measure of your own progress is.", SRC, "Mindset, Ch 4", "secondary_source", "expected", "distinguishes noticing from measuring")],
    "questions": ["Why does comparing myself to a friend make me feel worse even when I'm improving?", "What should I actually measure myself against?", "Is it wrong to notice other people are ahead?"],
    "misconceptions": [("Comparing to someone else's current position tells you how you're doing", "It only tells you the gap, which says nothing about your own growth.", "Ch 4"), ("Noticing someone else is ahead is unkind of you to think", "Noticing is fine; using it as your only measure is what misleads.", "Ch 4")],
    "pain_points": ["Feeling behind because a friend is ahead at something", "Losing sight of real progress by only looking sideways"],
    "angles": [("Two Footprints on One Path", "narrative", "Yesterday's footprint and today's footprint, on the very same path, tell you the only true story of your own progress.", "A concrete, repeatable image she can use on any skill.", ["Ch 4"]),
               ("The Gap That Lies", "contrarian", "The gap between you and someone else's path measures where they are, not how far you've come.", "Directly challenges the instinct to treat someone else's position as the real measure.", ["Ch 4"]),
               ("Noticing Is Not Measuring", "evergreen", "You can notice someone's ahead without making that your ruler.", "Separates an honest reaction from a harmful habit, so the lesson doesn't ask her to feel nothing.", ["Ch 4"])],
    "kahneman": "The only comparison that tells you the truth about your own growth is the one against your own past self.",
    "excluded": ["Sibling or classmate-specific comparisons, kept general so no real person is named."],
    "concepts": [
        {"id": "c1", "title": "Compare Yourself Only to Yesterday", "hook": "Diana, look down at the path behind you for a second, not at anyone else's.", "narrative_structure": "story",
         "visual_approach": "Two footprints on the same path, one behind the other, showing how far the same person has travelled rather than comparing to a different path entirely.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 135,
         "key_points": ["Looking sideways at someone else's path measures a gap, not your growth", "Looking back at your own footprint measures real progress", "Someone ahead of you says nothing about how far you've come", "This isn't about ignoring other people, just about what you measure yourself by", "Yesterday-you is the only fair comparison"],
         "core_message": "The gap between you and someone else was never the real story. The distance between yesterday-you and today-you is.", "cta": "Next time you compare, look back at your own footprint instead of sideways.", "tone": "Warm and grounding.",
         "why_this_works": "It replaces a banned comparison with a better one, rather than just telling her to stop comparing.", "grounded_in": ["Ch 4"]},
        {"id": "c2", "title": "The Gap That Lies", "hook": "That gap doesn't actually tell you anything true about you.", "narrative_structure": "problem_solution",
         "visual_approach": "A second, separate path visible in the distance, fading into the background beside her own.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 70,
         "key_points": ["The sideways gap measures someone else's position, not your growth", "It's easy to mistake that gap for a verdict on yourself"],
         "core_message": "The sideways gap was never measuring you.", "cta": "Notice when you're reading someone else's position as a verdict on yourself.", "tone": "Steady and clarifying.",
         "why_this_works": "Names exactly what the misleading comparison gets wrong, folded into c1 as its middle beat.", "grounded_in": ["Ch 4"]},
        {"id": "c3", "title": "Noticing Is Not Measuring", "hook": "You can notice someone's ahead without making that your ruler.", "narrative_structure": "problem_solution",
         "visual_approach": "Two paths shown side by side, both plain and simple, neither one dominant.", "suggested_playbook": "custom-atelier-storybook",
         "target_audience": "The same 8-year-old", "target_platform": "generic", "target_duration_seconds": 60,
         "key_points": ["Noticing is a normal, honest reaction", "The trap is only in using it as your only measure"], "core_message": "Noticing where someone else stands is fine. Measuring yourself by it is the trap.",
         "cta": "Let yourself notice without letting it become your ruler.", "tone": "Gentle and permission-giving.", "why_this_works": "Prevents the lesson from asking her to suppress a normal feeling, folded into c1 as its closing reassurance.", "grounded_in": ["Ch 4"]}],
    "rationale": "One clear image, footprint behind footprint, carries the whole idea without needing further concepts.",
    "device_short": "two footprints on the same path, one behind the other, measuring one person's own progress",
    "art_direction": "New device: a single path on cream paper showing two footprints from the same pair of shoes, one further back to represent yesterday, one further along to represent today.",
    "device_lock": "One simple path drawn on cream paper. Two footprint shapes on it, identical in size and style, one placed further back on the path than the other. No numerals marking distance, no second path or second person's footprints.",
    "tradeoffs": [{"tradeoff": "Showing a second child's path alongside hers versus showing only her own path twice", "recommendation": "Show only her own path twice",
                   "quality_impact": "A second path risks looking like a race against a specific rival; her own path shown at two moments keeps the comparison honestly self-directed."}],
    "energy_curve": "Grounding and calm from the opening. Curious at the footprint reveal. Gentle at the honesty about noticing others. Encouraging at the close.",
    "sample_section": "s6", "human_note": "Section s6 is the core reframe. Slow and certain.",
    "pause_beats": [{"section": "s4", "purpose": "She looks at the distance between the two footprints"}, {"section": "s9", "purpose": "She thinks of a comparison that's been bothering her"}, {"section": "s12", "purpose": "She picks something to measure against her own yesterday"}],
    "grounded_in": {"s1_to_s4": "Ch 4, the two footprints introduced", "s5_to_s8": "Ch 4, why sideways comparison misleads", "s9_to_s11": "Ch 4 applied to her own comparisons", "s12_to_s15": "Ch 4 corrective"},
    "sections": [
        ("s1", "Setup", "Diana, look down at the path behind you for a second, not at anyone else's.", "Diana, look down at the path behind you for a second, not at anyone else's.", 1.4, "measured", "warm", ["behind you"], "Grounding, physical instruction."),
        ("s2", "The sideways look", "It's so easy to look sideways instead, at somebody else's path, and measure the gap between you.", "It's so easy to look sideways instead, <break time=\"0.4s\"/> at somebody else's path, <break time=\"0.4s\"/> and measure the gap between you.", 1.4, "measured", "curious", ["the gap"], "Name the habit gently."),
        ("s3", "What that gap tells you", "But that gap doesn't actually tell you anything true about you. It just tells you where somebody else happens to be standing.", "But that gap doesn't actually tell you anything true about you. <break time=\"0.5s\"/> It just tells you where somebody else happens to be standing.", 1.4, "measured", "steady", ["somebody else"], "The core claim."),
        ("s4", "Your own footprints", "Now look at your own path instead. There's a footprint from yesterday, and a footprint from today.", "Now look at your own path instead. <break time=\"0.4s\"/> There's a footprint from yesterday, <break time=\"0.4s\"/> and a footprint from today. <break time=\"2.5s\"/>", 2.5, "slow", "curious", ["yesterday"], "Pause beat one. Let her picture both."),
        ("s5", "The real distance", "That gap, right there, between yesterday-you and today-you, is the only one that actually means anything.", "That gap, right there, between yesterday-you and today-you, <break time=\"0.4s\"/> is the only one that actually means anything.", 1.4, "measured", "warm", ["actually means"], "Reinforce the reframe."),
        ("s6", "The reversal", "So compare yourself to yesterday, Diana. Not to whoever happens to be ahead on a completely different path.", "So compare yourself to yesterday, Diana. <break time=\"0.5s\"/> Not to whoever happens to be ahead on a completely different path.", 1.4, "slow", "warm", ["compare yourself to yesterday"], "The heart of the film."),
        ("s7", "Not about ignoring others", "This doesn't mean you can't notice someone else is ahead. Noticing is fine. It's what you do with it that matters.", "This doesn't mean you can't notice someone else is ahead. <break time=\"0.4s\"/> Noticing is fine. <break time=\"0.4s\"/> It's what you do with it that matters.", 1.4, "measured", "gentle", ["noticing is fine"], "Guard against overclaiming."),
        ("s8", "The trap", "The trap is using someone else's path as your only ruler. Your own path already has one built in.", "The trap is using someone else's path as your only ruler. <break time=\"0.4s\"/> Your own path already has one built in.", 1.4, "measured", "steady", ["ruler"], "Explain the mechanism."),
        ("s9", "Her own comparison", "Think of a time comparing yourself to someone else made you feel worse, even though you'd actually improved.", "Think of a time comparing yourself to someone else made you feel worse, <break time=\"0.4s\"/> even though you'd actually improved.", 1.4, "measured", "gentle", ["actually improved"], "Real, specific reflection."),
        ("s10", "Reflect", "Have a think. It doesn't need to be a big thing.", "Have a think. <break time=\"0.4s\"/> It doesn't need to be a big thing. <break time=\"2.5s\"/>", 2.5, "slow", "gentle", ["doesn't need"], "Pause beat two. Keep it low-pressure."),
        ("s11", "It happens to me too", "This happens to me too, Diana, more than I'd like to admit.", "This happens to me too, Diana, <break time=\"0.4s\"/> more than I'd like to admit.", 1.4, "measured", "warm", ["happens to me"], "Genuine solidarity."),
        ("s12", "Pick something", "So pick one thing right now that you'd like to measure against your own yesterday.", "So pick one thing right now that you'd like to measure against your own yesterday. <break time=\"2.5s\"/>", 2.5, "measured", "encouraging", ["your own yesterday"], "Pause beat three. The actual instruction."),
        ("s13", "Check back", "Check it again tomorrow. Not against anyone else. Just against today.", "Check it again tomorrow. <break time=\"0.4s\"/> Not against anyone else. <break time=\"0.4s\"/> Just against today.", 1.4, "measured", "warm", ["just against today"], "Bright, forward-looking."),
        ("s14", "It adds up", "Small steps on your own path add up to somewhere real, even on days it doesn't feel like it.", "Small steps on your own path add up to somewhere real, <break time=\"0.4s\"/> even on days it doesn't feel like it.", 1.4, "measured", "steady", ["add up"], "Encouraging honesty."),
        ("s15", "Landing", "I'm not watching anyone else's path, Diana. I'm watching yours. And it's going somewhere good.", "I'm not watching anyone else's path, Diana. <break time=\"0.5s\"/> I'm watching yours. <break time=\"0.4s\"/> And it's going somewhere good.", 0.0, "slow", "tender", ["going somewhere good"], "Personal, warm, unhurried close."),
    ],
    "spec": [
        ("sc1", "s1", "DIANA", "The girl looks down at the ground behind her, thoughtful and grounded."),
        ("sc2", "s2", "NONE", "One simple path on the page with a second, separate path visible off to the side in the distance."),
        ("sc3", "s3", "NONE", "The distant separate path shown alone, fading into the background, unclear and unimportant."),
        ("sc4", "s4", "NONE", "One single path with two plain footprint shapes on it, one further back, one further along."),
        ("sc5", "s5", "NONE", "A close view of the space between the two footprints on the same path, clearly measurable and real."),
        ("sc6", "s6", "DIANA", "The girl looks steady and clear, taking in something important, calm expression."),
        ("sc7", "s7", "DIANA", "The girl looks thoughtfully toward something in the distance, calm rather than anxious."),
        ("sc8", "s8", "NONE", "One single path with a faint built-in marker line running along it, subtle and part of the path itself."),
        ("sc9", "s9", "DIANA", "The girl sits quietly, thinking, hand near her chin, genuinely reflective."),
        ("sc10", "s10", "DIANA", "The girl looks down in thought, calm and unhurried."),
        ("sc11", "s11", "NONE", "Two paths shown side by side, both plain and simple, neither one dominant or dramatic."),
        ("sc12", "s12", "DIANA", "The girl stands with one hand raised slightly, naming something, focused and clear."),
        ("sc13", "s13", "DIANA", "The girl looks forward with calm determination, settled."),
        ("sc14", "s14", "NONE", "A single path with several footprints spaced evenly along it, showing steady progress over time."),
        ("sc15", "s15", "DIANA", "The girl stands calm and warm in soft evening light."),
        ("sc16", "s5", "NONE", "The two footprints on the path glowing softly warm, the distance between them clearly highlighted."),
        ("sc17", "s14", "NONE", "The full path with its even spread of footprints, warm and settled, leading off into the distance."),
        ("sc18", "s15", "NONE", "One single path with a full trail of footprints leading toward warm evening light at the horizon."),
    ],
    "heroes": {"sc4", "sc16", "sc18"}, "wides": {"sc14", "sc17", "sc18"},
}
FILM9["clauses"] = {
    "OPEN": (G.OPEN, {"sc1", "sc6", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "NOICON": (G.NOICON, {"sc1", "sc6", "sc7", "sc9", "sc10", "sc12", "sc13", "sc15"}),
    "PATH": (("The path is a plain simple ground-level path drawn flat on cream paper, no landscape, no scenery. "
              "Footprints are plain identical shoe-print shapes. No numerals marking any distance."),
             {"sc2", "sc3", "sc4", "sc5", "sc8", "sc11", "sc14", "sc16", "sc17", "sc18"}),
}

if __name__ == "__main__":
    G_FILMS = {"m06": FILM6, "m07": FILM7, "m08": FILM8, "m09": FILM9}
    args = sys.argv[1:]
    slugs = [a for a in args if a in G_FILMS] or list(G_FILMS)
    for key in slugs:
        f = G_FILMS[key]
        if "init" in args:
            G.init(f)
        if "build" in args:
            G.build(f)
        if "sheet" in args:
            G.sheet(f)
